- README.md
I typed 'useradd' when I meant 'usermod' and worse, without the -a
flag it wipes out your other group memberships.
> [README] Fix bogus command to add user to group

- src/Makefile.base
This is required with recent versions of Newlib (as used by Zephyr SDK)
to access strnlen() and similar function. Similar define was added to
JerryScript Zephyr port upstream earlier.
> [Makefile] Define -D_XOPEN_SOURCE=700.

- arc/src/main.c
When the ipm message fails to allocate memory on the x86
for the IPM message, the message still gets sent as NULL,
the ARC doesn't check NULL messages and then segfaults.
> [ARC] Fix a segfault in ARC when IPM malloc fails

- src/zjs_callbacks.c
Fixes a DBG_PRINT which fails to compile when debugging is turned
on because j is an int, not a long unsigned.
> [callbacks] Fix for DBG_PRINT

- src/zjs_aio.c
- src/zjs_grove_lcd.c
We don't have to malloc heap memory for sending/receiving IPM
messages in sync API, since the ARC is guaranteed to receive the message
after the send() function returns, we can immediately free up
the IPM message, and so to make it more efficient, we just use
the stack memory to store the struct.
> [IPM] Use stack memory on ipm messages instead of malloc

- .travis.yml
This is the first iteration of enabling CI for the project. Each PR
and push command will trigger a message to the Travis CI infrastructure
which will attempt to build the project for the x86 (default), arc, linux
and Freedom Board targets, and report the results in the PR comments and
with an email. The exact behavior depends on the configuration selected
in the Travis CI control panel.
Signed-off-by: Francesco Balestrieri <francesco.balestrieri@intel.com>
> Add Travis CI configuration file to setup continous integration.

- Makefile
- deps/.gitignore
The prj.conf, prj.mdef, arc/prj.conf, and src/Makefile files are all
generated at build time, so add a comment to each to that effect and
delete them in make clean.
> [Makefile] Denote generated files with a comment and clean up on clean

- src/zjs_modules.c
Each module will now only be created once.  Additional calls to
requires("module") will return the previously created instance.
This will cut down on memory consumption and prevent unintended
behavior.
> [modules] Changing modules to use singletons

- src/ashell/jerry-code.c
- src/zjs_aio.c
- src/zjs_buffer.c
- src/zjs_console.c
- src/zjs_gpio.c
- src/zjs_ipm.c
- src/zjs_modules.c
- src/zjs_timers.c
This adds the necessary code to supply JerryScript with callbacks
to free memory when an object is garbage collected.  It also makes
the changes needed to ensure global JavaScript objects get GC'd.
Finally - it adds the code needed by ashell to be able to run
a ZJS JavaScript file multiple times without rebooting.
Signed-off-by: Brian J Jones brian.j.jones@intel.com
> [memory] Free global javascript objects and allow multiple restart

- src/zjs_k64f_pins.c
This is also what https://developer.mbed.org/platforms/FRDM-K64F/ lists.
Signed-off-by: Paul Sokolovsky paul.sokolovsky@linaro.org
> [zjs_k64f_pins] SW3 button is confirmed to be on PTA4.

- samples/tests/ButtonEnable.js
Following gpio.md, there is no gpio.on method, but onchange event instead.
> [Samples] Fix onchange event in ButtonEnable.js

- README.md
It should be "/etc/udev/rules.d" on Ubuntu 16.04
> [Documentation] Update udev rules

- docs/API.md
Signed-off-by: Francesco Balestrieri <francesco.balestrieri@intel.com>
> [docs] Add I2C API docs to the list of APIs

- Makefile.linux
- docs/API.md
- docs/performance.md
- scripts/analyze.sh
- src/Makefile.base
- src/zjs_modules.c
- src/zjs_performance.c
- src/zjs_performance.h
- tests/test-performance.js
~~~
Based on recent W3C API, formally defined in https://www.w3.org/TR/hr-time/
and informally in
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now . As the
last link suggests, real-world usage boils down to just:
t = performance.now();
even though formal spec defines more properties for "performance" object.
As defined in the spec for a browser, "performance" is a property of
global window object and thus implicitly present into context of a JS
script. We however define it as a module, so usage pattern is:
var performance = require("performance");
t = performance.now();
The returned value is a floating-point number of milliseconds since
arbitrary point in time. This means that its absolute value is
meaningless and only difference between 2 values make sense (and
represent …
> [performance] New module implementing performance counter API.

- src/ashell/jerry-code.c
- src/zjs_timers.c
- src/zjs_timers.h
Because ZJS implements its own version of setInterval,
the new code to release global objects had a unintended
effect of causing timers that didn't save the return to
be garbage collected after the first call. Now instead
of relying on JerryScript to GC our timers, we will clear
them ourself when jerry_cleanup runs.
> [timers] Changing how timers are released

- .travis.yml
- scripts/analyze.sh
James had a good point that we could have a simple test that just
requires everything; but this seemed more fun for the moment. Maybe
we could even generate that test from the module list to keep from
missing any? Needs a bit more thought.
> [travis] Add tests so that all modules get built

- docs/API.md
Cherry-pick of 66292ff6985cb0cbe7aa6f2b600c57700f43b5a6
> [docs] Add I2C API docs to the list of APIs (#387)

- .travis.yml
The previous method using HEAD~49 was based on the checkout having gone
to a depth of 50, but under certain circumstances it could fail as it did
for the test build of e9b8279 apparently.
> [travis] Fix git check to use rev-list to be sure it finds a good commit

- src/zjs_callbacks.c
The memory dedicated to the ring buffer is too large.  It is
causing ashell to fail to build because it won't fit.
> [ashell] Shrinking ring buffer size

- Makefile.linux
- src/zjs_performance.c
Also, fix warning now caught in performance module.
> [makefile] Add -Werror to Linux builds

- Makefile
I really wanted to warn but set it to deps/zephyr by default, but
couldn't figure out how to do that. This is a good improvement
though since it will only report an error if you actually need
Zephyr.
> [makefile] Report build error when ZEPHYR_BASE is not set

- Makefile
- This means that building in release mode THEN in debug mode will
cause the debug build to clean before rebuilding. This already
worked for Zephyr targets, but not on Linux
> [build] Added VARIANT to the .last_build file

- src/zjs_common.h
We don't want to miss errors when we're in release builds. Things for
debug only belong in DBG_PRINT.
> [general] Print ERR_PRINT messages in release builds

- arc/src/Makefile.base
- arc/src/main.c
- samples/Accelerometer.js
- samples/Gyroscope.js
- scripts/analyze.sh
- src/Makefile.base
- src/main.c
- src/zjs_ipm.h
- src/zjs_sensor.c
- src/zjs_sensor.h
Initial implementation for the W3C Generic Sensor API and add
support for the Accelerometer and Gyroscope sensors using
the BMI160 inertia sensor built-in on the Arduino 101,
the current implementation is polling from the ARC and channeling
the data back to X86.
Also adding two sample JS code testing both APIs.
> [Sensor] Initial implementation of the Generic Sensor API

- Makefile
This allows to build QEMU target for BOARD=qemu_cortex_m3, and in future,
for other QEMU target. This however now requires explicit BOARD when
build for x86:
make BOARD=qemu_x86 qemu
> [Makefile] Don't force BOARD=qemu_x86 for "qemu".

- README.md
Updating build instructions to reflect the changes now that
we have to build the ARC images to support the corresponding
x86 image.
> [Doc] Updated build instruction for x86 and ARC

- Makefile
- modules/BMP280.js
- modules/GroveLCD.js
- samples/I2CBMP280.js
- scripts/analyze.sh
- src/main.c
- src/zjs_modules.c
Users can now import Javascript modules using
var myObj = require("modulename.js");
A sample is also included to demonstrate how this is done.
> [modules] Add support for Node.js modules

- Makefile.linux
- The linux build now "builds" all its files under outdir/linux/
- The final executable is located under outdir/linux/<variant>/jslinux
> [build] Restructured the linux build

- samples/arduino/basics/Blink-k64f.js
- samples/tests/ButtonEnable.js
1. Fix onchange event in ButtonEnable.js
2. Use pins.LEDG instead of pins.D5 in samples/arduino/basics/Blink-k64f.js
> [Samples] Update ButtonEnable.js and Blink-k64f.js on zjs-0.1

- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_gpio.c
- src/zjs_promise.c
- src/zjs_timers.c
- src/zjs_uart.c
- Removed the union of C/JS structs so callbacks only do 1 allocation
- Changed callback ID's to int16_t's instead of int32_t's
- Changed all modules using calbacks to use int16_t's
> [callbacks] optimized callbacks

- tests/test-grovelcd-cursor-manual.js
- tests/test-grovelcd-ds-manual.js
- tests/test-grovelcd-rgb-manual.js
> [Tests] Add manual tests for Grove LCD APIs

- arc/src/main.c
- samples/Gyroscope.js
- scripts/analyze.sh
- src/zjs_ipm.h
- src/zjs_sensor.c
Added trigger support, since currently in Zephyr, triggers can
only be signaledfrom interrupt from x86 side, all the x86 side
code is wrapped with BUILD_MODULE_SENSOR_TRIGGER #ifdef so that
it can be turn off later when Zephyr changes.
The trigger are set to sample in 50Hz, any higher frequency
will cause the ring buffer to start dropping change events.
> [Sensor] Added support for trigger mode

- src/zjs_callbacks.c
- src/zjs_promise.c
- src/zjs_timers.c
- Also fixed debug build relating to the callback change
> [callbacks] Fixed broken callbacks after optimization change

- Makefile
- Makefile.linux
- src/Makefile.base
- src/zjs_console.c
- To print floats on the A101, a flag had to be used which added
~11k to our ROM footprint. This adds a compile time option to
enable this flag. It is disabled by default so if a float is
printed it will approximate the value e.g.
[Float ~42]
instead of (with the flag enabled):
42.424242
> [build] Added flag to toggle print float flag

- src/ashell/jerry-code.c
- src/zjs_buffer.c
- src/zjs_buffer.h
- src/zjs_util.c
- src/zjs_util.h
This should save lots of runtime JS memory when there are multiple
buffers instantiated because only the single prototype needs to contain
the mappings to native API functions. I'd like to measure how much this
saves but expect we should replicate it across all APIs.
Also, added a zjs_obj_add_functions (plural) API to simplify creating a
large batch of native API mappings for an object.
Also, reorder cleanup for ashell so that jerry_cleanup() is the final
step and should leave the JS memory in its pristine state.
> [buffer] Use prototype inheritance to implement Buffer functions

- .gitmodules
JerryScript moved their repository into jerryscript-project
Changed the .gitmodules to reflect the move.
Signed-off-by: Sergio Martinez <sergio.martinez.rodriguez@intel.com>
> [build] Moved JerryScript repo into the new url

- Makefile
- fragments/zjs.conf.dev
- scripts/analyze.sh
- src/Makefile.base
- zjs.conf
Now make can be given CONFIG=zjs.conf (or whatever file you choose)
to indicate you want certain modules to be built in.  This allows
you to build modules that aren't included in your Javascript file.
This will also allow us to build ashell, linux, etc with only the
modules we want rather than all of them.  In the future we can
remove the #ifdef BUILD_MODULE* from the src files as they simply
won't be included in the build rather than commented out.
> [build] Adding configuration file support for the build

- src/ashell/Makefile
- src/ashell/comms-shell.c
- src/ashell/comms-shell.h
- src/ashell/comms-uart.c
- src/ashell/comms-uart.h
- src/ashell/file-utils.c
- src/ashell/ihex-handler.c
- src/ashell/jerry-code.c
- src/ashell/main-zephyr.c
- src/ashell/shell-state.c
- Changed nano_fifo to k_fifo apis
- Since we are working on getting webusb and bluetooth integrated
to upload the javascript code, acm_ doesn't make much sense anymore.
We are renaming the methods from acm into a generic communications 'comms',
so we also avoid clash with the acm driver methods.
Signed-off-by: Sergio Martinez <sergio.martinez.rodriguez@intel.com>
> [ashell] Updated fifo APIS & Refactor of acm into comms

- scripts/trlite
With no args, runs all the tests.
"trlite zephyr" runs just the VM #1 "zephyr" tests.
"trlite linux"  runs just the VM #2 "linux"  tests.
"trlite ashell" runs just the VM #3 "ashell" tests.
You can also just pass the VM# instead (1, 2, or 3).
> [scripts] New script 'trlite' to run Travis tests locally

- src/zjs_callbacks.c
- Fixes promises which broke after callback optimization change
> [callbacks] Fixed zjs_edit_js_func()

- src/ashell/jerry-code.c
- src/zjs_aio.c
- src/zjs_aio.h
- src/zjs_modules.c
- src/zjs_modules.h
Also, add a spot for a cleanup function to be registered with modules
that will be called by a new zjs_modules_cleanup function. Currently,
this is called only in ashell.
Also, fix what appeared to be a bug where module instances weren't
being released.
> [aio] Use prototype inheritance to implement AIO functions

- scripts/trlite
To do this, take the current git diff of the tree and apply that patch
within the .trlite directory.
Also, report the ZJS_BASE dir being used and the diffstats of the
uncommitted changes found to help the user be sure they're building
what they intended.
> [trlite] Preserve uncommitted changes in the tree for trlite tests

- arc/src/main.c
- samples/AmbientLight.js
- scripts/analyze.sh
- src/zjs_ipm.h
- src/zjs_sensor.c
Extend GenericSensor API to support AmbientLightSensor of W3C,
added support for the Grove Light sensor that comes from the
standard Grove Starter Kit for Arduino 101.  The sensor is designed
to be connected to the analog pins on the board.
> [Sensor] Add support for AmbientLightSensor

- tests/test-performance.js
With upgrade to Zephyr 1.6 and refactors on Zephyr.js side, we're now
seeing delta of 20ms on both arduino_101 and frdm_k64f.
> [tests] test-performance.js: Bump delta to 21ms.

- scripts/convert.sh
Because printf was being used, the % character would have needed special
treatment to avoid a warning.
Also, the dots were overflowing past the end of the line in output which
looked bad after it hit 90%.
Fixes issue #490.
> [convert] Fix conversion of % characters, also limit output line length

- Makefile.app
This will further reduce final build size by 5-6k, the
default Zephyr target in JerryScript do not have these
enabled.
> [JerryScript] Optimize build with LTO and All-in-one flags

- README.md
This is to help address issue #513.
> [osx] Update README with links to Zephyr non-Linux instructions

- Makefile.linux
OSX do not have the cp --parents. rsync -R does the job.
> OSX: use rsync since cp --parents is not avilable

- Makefile
- Makefile.linux
- Makefile.snapshot
- src/Makefile.base
- src/main.c
- src/snapshot.c
The snapshot build is enabled by passing SNAPSHOT=on to make,
this will build a snapshot tool that will first parse the JS
script, and generate a zjs_snapshot_gen.c file that stores
the byte code of the running JS, and then the main program
will just run the snapshot byte code instead of parsing
the JS at run time.
For example:
$ make JS=samples/AIO.js SNAPSHOT=on all
$ make dfu-all
> [Snapshot] Enable snapshot build feature

- src/zjs_buffer.c
Currently, Buffer will crash if it tries to free the last item,
because freeing it tries to look at the ->next of NULL. This adds
an extra check and also now returns once the handle has been freed,
since there's no reason to keep going.
> [bugfix] Buffer will fail if freeing the last item

- src/zjs_ble.c
Currently update notification is sent immediately after a client
connects, this patch will now monitor subscribe/unsubscribe
events from client, fixes bug#349
> [BLE] Fixed auto notification subscription upon connect

- Makefile
We put it there in "jerryscript" target, so there's nobody else but us
to remove it from there.
> [makefile] Explicitly remove libjerry-core.a on "make clean".

- src/zjs_gpio.c
Previously, it was a fatal error if GPIO_0 device didn't exist. Now,
print a (warning) message, but continue. This change allows to run
Zephyr.js on other boards than just arduino_101 and frdm_k64f.
> [GPIO] Don't assume that GPIO_0, etc. exist.

- samples/I2C.js
- scripts/analyze.sh
- src/Makefile.base
- src/zjs_i2c.c
- src/zjs_i2c_ipm.c
This is the code to add I2C support for non-ARC boards such as the
FRDM-K64.
> [i2c] I2C functionality for non-ARC boards

- scripts/analyze.sh
- src/Makefile.base
- src/zjs_grove_lcd_ipm.c
Create a non-ipm version of the Grove LCD that will build
and run on the Zephyr boards that do not have ARC.  Move all
existing IPM code to a new module zjs_grove_lcd_ipm that gets
build only for Arduino 101.
> [Grove LCD] Make Grove LCD work on the FRDM-K64F boards

- Makefile
- Makefile.linux
Update JerryScript to support building without parser, and
enable snapshot by default.
> [Snapshot] Update JerryScript

- scripts/checkheaders
- src/zjs_uart.h
Also, hide details unless -v is specified to summarize more easily
spot where the problems lie, and whether you care to look into them.
> [checkheaders] Update script to overlook false positives

- scripts/trlite
Changes that you have already staged with git-add were not being applied
to the trlite clone of the repo, so you would get unexpected results
running trlite in that state.
> [trlite] Preserve cached (staged) changes in trlite builds

- docs/uart.md
- Documentation said that UART could use tty1, which was not true
and would cause an error to be thrown. The error will still be
thrown, but the docs now only mention tty0.
> Changed UART docs to reflect proper usage

- Makefile.linux
- iotivity-constrained broke the build on Mac. This patch only includes
the OCF API's on Linux
> [OCF] Make OCF only build on linux.

- src/main.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_modules.c
- src/zjs_modules.h
- src/zjs_ocf_common.c
- src/zjs_ocf_common.h
- src/zjs_timers.c
- src/zjs_timers.h
- Passing in "--autoexit" will cause jslinux to terminate if no
callbacks or timers were processed on the current or previous
main loop.
- Passing in "-t <time>" will cause jslinux to terminate after
<time> milliseconds>.
- Both new flags can be used at the same time if desired.
> [general] Added exit features to linux target

- scripts/trlite
My last change included staged changes, but accidentally dropped
unstaged changes. Now finally we'll have both.
> [trlite] Preserve staged AND unchanged changes in trlite

- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_grove_lcd.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_i2c.c
- src/zjs_i2c_ipm.c
- src/zjs_sensor.c
Fix for issue #549.  This was caused by having too short of a IPM
timeout.  Extending the timeout solves the issue, allowing multiple
modules to be using IPM without issue.
> [bugfix] Extending the IPM timeout

- src/zjs_modules.c
We've turned off -Werror for a little while so it's harder to notice
when this happens.
> [modules] Fix warnings from recent update to modules code

- scripts/analyze.sh
This will fix the error flooding Accelerometer events in
bug #504, although it doesn't fix the bug where Accelerometer
will report 0 on all axis, that's a separate bug.
> [Sensor] Updated BMI160 configs

- .travis.yml
- scripts/trlite
This is to force people to use the new zjs_copy_jstring and
zjs_alloc_from_jstring. These calls require a maximum size to avoid
overflowing the stack or missing a null terminator.
> [travis] Disallow new calls to jerry_string_to_char_buffer

- src/zjs_i2c_ipm.c
This fixes issue #557 where the Grove LCD backlight wasn't changing
color on the Arduino101.
> [bugfix] Fix backlight on A101

- arc/src/main.c
- src/zjs_i2c.c
- src/zjs_i2c.h
- src/zjs_i2c_ipm.c
This is a fix for issue #551, now an error will be thrown if the
I2C bus fails to open.
> [bugfix] I2C will now throw an error if bus fails to open

- src/zjs_buffer.c
- src/zjs_i2c.c
- src/zjs_i2c_ipm.c
- src/zjs_util.c
- src/zjs_util.h
> [buffer] Make length attribute read-only

- Makefile.snapshot
Fixes issue #588 where snapshot was failing to build since it
didn't have the path to the new zjs_common.c file.
> [snapshot] Adding file path for new zjs_common.c

- src/zjs_linux_port.h
CLOCK_MONOTONIC was not defined.
> [osx] fix make linux on osx

- Makefile.linux
- src/Makefile.base
- src/main.c
- src/zjs_error.c
- src/zjs_error.h
- src/zjs_modules.c
- src/zjs_util.c
- src/zjs_util.h
- tests/test-error.js
These are defined by Zoltan's iot-js-api. It works to check them with
the .name property or instanceof, the latter due to lots of painful
experimentation so you better use it!
Also, update native_require_handler to use the new standard error
macros and test these along with error constructors in a new
test-error.js file.
> [error] Implement standard error types

- src/zjs_ble.c
Removed a struct that wasn't needed because one of two fields was
never used.
> [ble] Simplify definition of ble_conn, other cleanups

- samples/BootTime.js
- samples/I2C.js
- samples/WebBluetoothGroveLcdDemo.js
- tests/test-performance.js
Add new BootTime.js sample that does nothing but this check, since
it didn't seem appropriate to add to HelloWorld.js.
Addresses issue #611.
> [perf] Add boot timestamps to key samples for QA measurement

- scripts/analyze.sh
Previously, detection expected a numeric argument, e.g. `new Buffer(8)`,
but it can also be called with a string, like `new Buffer("foo")`. So,
support any argument (including still supporting none at all).
> [analyze] Detect Buffer constructor with any arguments.

- samples/Console.js
- src/zjs_console.c
- src/zjs_modules.c
Works without malloc or adding a JS object for each timer.
Also, add cleanup function to release the global time object.
> [console] Simplify time/timeEnd implementation with JS object

- src/zjs_buffer.c
> [buffer] Remove unnecessary include of zephyr.h

- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_ble.h
- src/zjs_buffer.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_console.c
- src/zjs_event.c
- src/zjs_event.h
- src/zjs_gpio.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_i2c.c
- src/zjs_modules.c
- src/zjs_promise.c
- src/zjs_sensor.c
- src/zjs_uart.c
- src/zjs_util.c
The document 06.REFERENCE-COUNTING.md in JerryScript makes it clear
now how and when jerry_value_t items must be released. In particular,
you're not responsible to release values passed in to you, but any
function that returns a value is giving you a "live" reference to
it that you must release. But when you return from a native function,
you transfer ownership of the returned value back to JavaScript.
In particular, even the error value that functions return is supposed
to be released, which we rarely if ever did before this review.
Reviewed all code in src/*.c except for the OCF files which were too
foreign to me to address correctly.
> [general] Review and correct lifetime of jerry_value_t items

- docs/API.md
Always a good idea to alphabetize: helps the users find what they're looking
for, helps us avoid duplication when the list gets longer, etc.
> [docs] Alphabetize API document list

- Makefile.linux
- src/zjs_buffer.c
- Fixed minor overflow bug that Linux compiler warned about.
> Enabled buffer support on Linux

- Makefile
- Makefile.linux
- To clean, you must specify the BOARD you want to clean for. Not specifying
BOARD will result in the default (Arduino 101) getting cleaned.
- To build for Linux, you now specify BOARD=linux. This matches all the other
targets. To clean for linux you must also specify BOARD=linux.
- Fixed the jerryscript clean issue where the library was not getting removed
during a clean, hence JrS would use the old stale library.
> [make] Made make HW support more consistent

- modules/Assert.js
This improves the basic syntax to:
var assert = require('Assert');
assert(true, "successful assertion");
assert(false, "failed assertion");
Also allow any "truthy" value to pass. If you explicitly want to check for
exact equality with true, then do:
assert(operation() === true, "perform operation");
Relax about argument types; equal can check non-object arguments. The
description argument can be a non-string or doesn't have to be given.
Swapped argument order in assert.throws() to match Node API.
> [assert] Make the QA Assert module match Node APIs better

- Makefile.linux
- Moved standard linux options to top of Makefile.linux, and
optional ones (OCF) to the bottom
> [build] Fixed OSX buffer build

- samples/I2C.js
- src/zjs_buffer.c
This bug was hit if you tried to pass the fourth encoding parameter
to the function; it would get an error even if you passed 'utf8'.
Also, cleaned up indentation issue in I2C.js.
> [buffer] Fix bug with uninitialized buffer in write_string

- Makefile
Also, remove the entire JerryScript build directory which got dropped
somehow. (This cleans builds for all boards at once.)
> [build] Fix pristine target to remove all locally created files

- src/zjs_i2c.c
- src/zjs_i2c_handler.c
- src/zjs_i2c_handler.h
- src/zjs_i2c_ipm_handler.c
Also fixing the return type to be int, since that's what
zephyr returns.
> [bugfix] Fixing #651 to remove compiler warnings

- src/zjs_callbacks.c
If not done like that, any JS callback which takes arguments must be
accompanied by "post" function which will release those arguments,
which is quite cumbersome.
> [zjs_callbacks] Automatically release JS callback args.

- src/zjs_ble.h
- src/zjs_buffer.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_event.c
- src/zjs_event.h
- src/zjs_gpio.c
- src/zjs_promise.c
- src/zjs_timers.c
Enforce rule that ring buffer owns JrS values stored in it. They are
acquired in zjs_signal_callback and released in zjs_service_callbacks.
Various other minor cleanups.
This was inadvertently left out of my patch in commit 8d6571a.
> [callbacks] Correct lifetime of jerry_value_t items in callbacks

- scripts/analyze.sh
- src/zjs_i2c_handler.c
The I2C device driver name for sensor sub-system is "I2C_SS_0", not "I2C_0",
updating both I2C and Grove LCD to use the new driver name
> [I2C] Fixed broken I2C and Grove LCD

- .travis.yml
- Makefile
- scripts/trlite
- Added depricated error if user tries to build with "make linux"
instead of "make BOARD=linux"
> [build] Fixed linux build break

- Makefile
- Makefile.snapshot
The -DDEBUG_BUILD flag in the snapshot Makefile was causing
issues after make pristine, the snapshot_gen tool do not
need to a debug build anyway, so cleaning up the Makefile to
fix breakage.
> [build] Fix debug build fail after make pristine

- src/ashell/webusb-handler.c
Whitelist the Zephyr.js IDE url (https://01org.github.io/zephyrjs-ide) and make it as default landing page.
> [webusb] Whitelist the Zephyr.js IDE url

- Makefile
- README.md
- scripts/trlite
Akin to recent patch to make ROM allocation configurable in the make
command, do the same for RAM. By default in Zephyr on Arduino 101, the
first 1K of 80K RAM is allocated for special purposes, then the next
24K is allocated for ARC and the next 55K for X86. Now we allow this
to be overridden with the RAM= command line argument. It specifies the
X86 RAM so it can range from 55-79. (It could be made lower if we see
the need for that later.)
Also, change the new SIZE argument to be ROM to distinguish it from
the new RAM option.
Add some output at the beginning of an Arduino 101 build that reports
the RAM/ROM values being used.
Revert part of the other patch that added SIZE argument to UART
builds in Travis/trlite because it doesn't seem necessary after all.
Update the README to reflect the …
> [build] Adjust RAM allocation boundary between x86 and arc

- Makefile
Using 'make rom_report' or 'make ram_report' with Zephyr targets, you
get a list of all the symbols defined and how big they are, to try to
identify space hogs.
> [build] Add passthrough support for Zephyr ram/rom_report targets

- Makefile
- Makefile.snapshot
- src/snapshot.c
Backported patch from master that fixes building with SNAPSHOT=on
and make the default build to use the snapshot feature.
> [build] Fix building of SNAPSHOT=on

- Makefile
There's a bug in the build when snapshot is enabled,
it generates snapshot from the JS that's passed, but
it should be generating from the /tmp/zjs.js file which
contains other JS modules.
> [build] Fixed failed to require JS modules

- src/snapshot.c
Fixed a bug in snapshot tool that incorrectly passes the length
of script which results in the tool failing to parse certain JS samples.
> [snapshot] Fixed bug that passes incorrect length using snapshot

- scripts/analyze.sh
The previous patch accidentally downgraded the commit of Zephyr,
and the patch the fixes the bmi160 sensor was not the correct one
since it wasn't a valid test, this is the correct fix and also
revert Zephyr commit to latest.
Also filed bug on Zephyr upstream and submitted fix ZEP-1704
> [sensor] Proper fix of BMI160 and update Zephyr

- src/zjs_sensor.c
This fixes a nasty bug that in the sensor module, it was calling
a jerry_function in the IPM callback which is a interrupt callback,
and it will cause the app to hang randomly when the frequency is
set at a high rate like more than 20Hz.
The lesson here is that we should really make sure we are not calling
into JerryScript engine directly or indirectly through one of our
helper functions inside a interrupt such as IPM message handlers.
> [sensor] Fixed random hang after when frequency is set too high

- scripts/trlite
Instead of test building with a random smattering of our sample apps
(at one time chosen for their spanning all of our available modules)
just write out one-line .js files to test with that will cause
individual modules to be built.
Also add cases to cover snapshot off as well as on, the a101 sensors,
print float feature, debug build, and ram size change.
> [trlite] Test each module individually; sensors, snapshot, debug

- scripts/trlite
The script was returning a zero value even on failure, so Travis always
succeeded, which felt warm and fuzzy, but wasn't.
Also, realized try_func is no different than try_command, so it could
be removed.
> [trlite] Fix to return error value properly

- scripts/analyze.sh
Zephyr has updated which the previous fix the Grove LCD is no
longer needed and will not run properly if kept, thus removing
the existing config.
> [Grove LCD] Fixed Grove LCD broken after Zephyr update

- Makefile
> [build] Make ROM default 256 to minimize need for specifying it

- Makefile
This gives more useful debugging messages to developers to catch
syntax errors in their Javascript.
> [build] Added uglifyjs for catch parse errors when building snapshot

- src/main.c
- src/zjs_ble.c
We used to enable it from outside the BLE module, but on ashell
this meant the module hadn't been initialized yet, because there is
no JS running with a require() call initially.
This fixed a spurious zjs_call_callback() error message on ashell
startup, and also allows apps like BLE.js to be run from ashell!
> [ble] Enable BLE from ble_init function

- src/ashell/jerry-code.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_modules.c
This adds a method that ensures all callbacks are freed.  It
also changes the order of some of the cleanup functions to
ensure stability when starting / stopping apps using ashell.
> [ashell] Adding code to free cb memory and change cleanup order

- src/zjs_ble.c
Instead of a hard-coded fake Bluetooth MAC address, retrieve
the real MAC address when client connects or disconnects.
> [ble] Remove hard-coded Bluetooth MAC address

- Makefile
- docs/dgram.md
- samples/UDPEchoServ4.js
- samples/UDPEchoServ6.js
- scripts/analyze.sh
- src/Makefile.base
- src/zjs_dgram.c
- src/zjs_dgram.h
- src/zjs_modules.c
This implements basic subset of "dgram" module, per https://github.com/01org/zephyr.js/issues/386. It support both IPv4 and IPv6, and implements enough functionality for a UDP echo server (examples included).
This is now ready for review, and some points to pay to:
~~1. Some things aren't yet implemented, like buffer offset/size in .send(), args to send callback, etc.~~
2. JrS API is verbose, that's why zjs_util.c exists, but I find even that verbose too. Repetitive boilerplate code just calls to be hidden behind macros, and that's what I did. Let me know if you like, and they can be made ZJS_GET_STR(), etc., and moved to zjs_util.h . Otherwise, if you don't like it, tell me what I should do.
3. Error handling in C is also verbose and cumbersome. Why the CHECK() macro. It's not supposed …
> "dgram" (UDP) module

- src/zjs_gpio.c
This fixes the issue where GPIO was not having it's zjs_gpio_close function called because we still had a reference to the onchange function when jerry_cleanup gets called.  Now the garbage collector will clean the GPIO object like it should.
> [gpio] Fix to allow JerryScript to release onchange callback

- scripts/convert.sh
Fixed a bug in the convert.sh script where it could add a newline
to the generated C string when the input JS contains a newline at
the end of the file after running through uglifyjs.
> [build] Fixed invalid C string genereated when SNAPSHOT=off

- samples/I2C.js
The ashell build doesn't include perf module so this sample doesn't
run, but the perf line is just for QA so it should be optional.
> [samples] Make perf module optional in I2C.js

- docs/dgram.md
Also, tested wildcard addresses to work for bind, so included in the
docs too.
> [dgram] Clarify description of an address which should be used in bind().

- src/main.c
- use --noexit to run indefinitely
> [linux] Set Linux auto exit feature to default

- src/zjs_modules.c
This is to match behavior of a module not being built into a real
build, so that test-error.js will see the same error type.
> [error] Make missing JS module a NotSupportedError in linux build

- src/zjs_console.c
- src/zjs_error.c
- src/zjs_error.h
This means instanceof AssertionError won't work but you can still test
the name; since this comes from one console function it doesn't seem
like it should be considered a standard error.
Fixes issue #735.
> [assert] Demote AssertionError from standard to custom error

- src/zjs_util.c
- src/zjs_util.h
This allow the readonly properties to be modifiable in native
so objects can update the property or delete them if needed.
Also adding a new helper method that can delete a property.
> [util] Fix add_readonly_string to set configurable

- src/main.c
The message looked like an error had occurred, when this was normal
operation. Mitigating that somewhat, but maybe we should do away with
the message entirely.
> [jslinux] Improve output at termination

- src/zjs_util.c
If the object doesn't not have the property set it will still
return true since there's no error, but the numeric values
are invalid
> [util] Fixed bug where util functions don't check for valid number value

- modules/GenericSensor.js
- src/zjs_sensor.c
The default state is no longer "idle" and should be "unconnected",
also it should be a readonly property, and readings should also
be readonly as well
> [sensor] Added default state "unconnected"

- src/zjs_promise.c
- src/zjs_test_promise.c
- Fixed OCF on linux by updating iotivity-constrained
(client + server compiled in previously did not work)
> [ocf/promises] Fixed OCF crash because of bug from promise patch

- src/zjs_sensor.c
Sensor tests are broken because because the callstack is corrupted
when sending IPM messages, and this patch rewrite the start sensor
logic to have a callback that's called from the mainloop instead
for a smaller call stack.  Also fixed an issue where stop fails
on AmbientLightSensor
> [sensor] Fix sensor to pass unit test

- src/zjs_callbacks.c
This makes sure we don't cascade into bigger problems with our
ringbuf error reporting.
> [callbacks] Back off ring buf reporting over time

- samples/SensorBLEDemo.js
It looks like without any prints, we can achieve a maximum of 100hz
for sending sensor data over BLE, seeing only a few dropped ring buffer
errors.
> [demo] Increase sensor frequency to 100

- scripts/trlite
If you have a long list of files changed in your current tree, the
pager would kick in and put you in 'less' in your terminal, missing
the trlite output.
> [trlite] Turn off paging in git commands to avoid issue

- docs/fs.md
- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_buffer.c
- src/zjs_console.c
- src/zjs_dgram.c
- src/zjs_error.c
- src/zjs_event.c
- src/zjs_fs.c
- src/zjs_gpio.c
- src/zjs_grove_lcd.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_i2c.c
- src/zjs_modules.c
- src/zjs_ocf_ble.c
- src/zjs_ocf_client.c
- src/zjs_ocf_server.c
- src/zjs_promise.c
- src/zjs_pwm.c
- src/zjs_sensor.c
- src/zjs_test_promise.c
- src/zjs_timers.c
- src/zjs_uart.c
- src/zjs_util.c
- src/zjs_util.h
- tests/test-buffer-rw.js
The new ZJS_VALIDATE_ARGS macro and related macros are to be used at
the top of any JerryScript C binding to verify the quantity and types
of arguments, and return standard exceptions if there is a problem.
The comments above the macros in zjs_util.h explain the details of how
they are to be used.
> [util] Add macros/functions to standardize argument validation

- docs/aio.md
- src/zjs_aio.c
The device, name and raw properties are all unused, so
removing these for fixing #794.
> [aio] Remove unused parameters in open

- scripts/analyze.sh
There is an issue with ADC when SDK version 0.9 is used and that is
causing a hang during the device boot (Zephyr issue- ZEP-1882). The
root cause seems to be some compiler optimization in GCC version
used in the SDK v0.9. So, this patch adds a workaround that enables
debug mode when SDK v0.9 is used and ADC is included in build.
> [scripts] Enable debug mode when building ADC with SDK 0.9

- src/zjs_util.c
- src/zjs_util.h
Add missing zjs_obj_add_readonly_boolean function
Add zjs_set_readonly_property function for handling generic objects
> [util] fix up add_readonly functions

- src/zjs_dgram.c
Avoiding magic numbers is good, but here the magic is explained in the
line directly above, nicer than sizeof(args) / sizeof(jerry_value_t).
> [dgram] Fix bug in passing argument count

- docs/sensors.md
- modules/GenericSensor.js
- samples/Accelerometer.js
- samples/AmbientLight.js
- samples/Gyroscope.js
- samples/SensorBLEDemo.js
- src/zjs_sensor.c
The readings no longer are passed to the event object
in the onchange() callback, but instead stored
as a internal property in the object itself in the
latest W3C spec.
> [sensor] Update sensor API for readings

- Makefile.linux
- src/Makefile.base
- src/ashell/Makefile
- src/ashell/jerry-code.c
- src/ashell/webusb-handler.c
- src/zjs_ble.c
- src/zjs_callbacks.c
- src/zjs_callbacks.h
- src/zjs_event.c
- src/zjs_event.h
- src/zjs_gpio.c
- src/zjs_modules.c
- src/zjs_promise.c
- src/zjs_promise.h
- src/zjs_sensor.c
- src/zjs_uart.c
Add one exception for format errors to allow iotivity-constrained build
to succeed, but we should follow up with a patch to that project.
Also, add the flags to linux and ashell builds, for the first time.
> [build] Re-enable warnings as errors

- src/main.c
- src/snapshot.c
- src/zjs_script.c
- src/zjs_script.h
- src/zjs_util.c
- src/zjs_util.h
If we get a malloc failure, it may be because there are JavaScript
objects that hold references to C memory through handles that can't
be freed until they are garbage collected.
This fixes issues #757.
> [util] Run JrS garbage collection and retry upon malloc failure

- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_console.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_promise.c
- src/zjs_util.c
uint32_t is now (properly) defined as unsigned int, instead of unsigned
long, which we'd worked around with incorrect format specifiers for the
last year.
Fixed the warnings from building HelloWorld and WebBT demo so far.
> [general] Fix format warnings that appear with SDK 0.9

- scripts/trlite
- src/zjs_dgram.c
Now dgram module will build in trlite to catch future bugs earlier.
> [dgram] Fix error introduced by ZVAL patch, add dgram to trlite

- src/zjs_i2c_handler.c
I2C will now throw an error if you try and access the
I2C_SS_1 bus on Arduino 101, since it's not connected
to anything.
> [i2c] Disallow invalid bus #1 on Arduino 101

- scripts/trlite
- src/ashell/Makefile
- src/ashell/jerry-code.c
- src/ashell/shell-state.c
Instead of DEV=ashell you now pass an ashell or ide target. Currently,
then only differ by one config line but I build both in Travis to catch
possible future changes.
Also, fixed a build error and a few format warnings w/ 0.9 SDK.
> [trlite] Update to build ashell the new way

- scripts/trlite
Only works for .c, .h, and .js files currently. Checks files modified in the
current commit. Checks that the very first line contains a copyright and that
it contains the current year in it.
> [trlite] Check that copyrights have been updated in modified files

- src/snapshot.c
JerryScript has changed the snapshot bytecode from uint8_t
to uint32_t, therefore we need to update the generated array
to store the increased byte code size
> [snapshot] Fixed broken snapshot build due to updated JerryScript

- arc/src/main.c
- src/zjs_ipm.h
- src/zjs_sensor.c
Allow app to pass sensor driver name by setting controller
string in constructor, for Accelerometer and Gyroscope, the
default controller is "bmi160"
> [sensor] support for different controllers in constructor

- README.md
> [docs] Added QEMU networking docs and created README index

- Makefile
- Makefile.linux
- scripts/convert.sh
- src/Makefile.base
- src/main.c
- tools/Makefile.snapshot
- tools/snapshot.c
Move the source and Makefile to tools directory, update snapshot tool
and convert.sh to generate just the needed bytes into header file, and
clean up the Makefile to build using the generated header in the outdir,
this should clean up all the generated src files in the root directory
> [snapshot] Clean up snapshot tool

- docs/ocf.md
- src/zjs_ocf_ble.c
- src/zjs_ocf_ble.h
- src/zjs_ocf_common.c
- Setting the BLE address was broken due to these two
configurations conflicting
> [ocf] Fix ocf.setBleAddress() and BLE_ADDR

- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_dgram.c
- src/zjs_fs.c
- src/zjs_gpio.c
- src/zjs_sensor.c
I introduced two bugs to zjs_dgram.c because of my recent argument
validation patch, where I got confused about whether zjs_signal_callback
was taking its size in bytes (right!) vs. number of values (wrong!).
We use bytes because the callback mechanism doesn't only hold JS values
but sometimes C values that might be different sizes than 4 bytes.
I found at least one other bug, and then also cleaned up the size
calculations to not rely on magic numbers when a fixed array (etc.) was
available for the compiler to do the math, per pfalcon's suggestion.
> [general] Fix calls to zjs_signal_callback

- src/zjs_callbacks.c
- Promises add undefined functions for then/catch, and if
then/catch are never called, callbacks was signaling on
an undefined function.
> [callbacks] Add check if JS function is undefined (#797)

- Makefile
- docs/ashell.md
- scripts/analyze.sh
- src/Makefile.base
This will also cause DEV=ashell to no longer be supported. This
helps remove confusion about building ashell the proper way.
> [build] Changing DEV to ASHELL to make things clearer

- tests/test-fs.js
**ISSUE:**
[ISS#886](https://github.com/01org/zephyr.js/issues/886) [fs] Read data that existed in r file failed when first run after power on
**TOTAL:** 33 of 33 passed
> [tests] Import Assert module for test-fs.js

- src/zjs_buffer.c
This follows Node.js docs for v6.10.1, although the constructor like
this is deprecated and really should change to Buffer.alloc().
> [buffer] Return a 0-length buffer if given negative size

- arc/src/main.c
- src/zjs_common.h
- src/zjs_sensor.c
Change controller from a char* to array so that it can be overwritten,
akso make default controller for AmbientLight to be "ADC_0" and
fix a leak
> [sensor] Fixed bug where controller name can't get set

- scripts/trlite
It was silly to do each module test by itself, this just took forever
and didn't really add anything.
> [trlite] Collapse module tests into one to speed things up

- tests/test-grovelcd-ds-manual.js
- tests/test-grovelcd-rgb-manual.js
The index counter has been incremented passed the length of
the array and therefore accessing the array throws an undefined
object exception.  The fix here to simply return the function
to abort the rest of the tests after tests are complete.
> [tests] Fix exception thrown after grove lcd manual tests

- docs/pwm.md
- samples/PWM.js
- samples/WebBluetoothDemo.js
- samples/arduino/basics/Fade.js
- samples/arduino/starterkit/ColorMixingLamp.js
- src/zjs_modules.c
- src/zjs_pwm.c
- src/zjs_pwm.h
- tests/test-pwm.js
This is a wise API choice because you can go through invalid states
by setting the wrong one first, where the pulse width is bigger than
the period. I convinced Zephyr itself to make this change, but we
hadn't gotten around to reflecting this in our own API.
Fixes #359.
> [pwm] Require PWM period/pulseWidth to be set at the same time

- docs/a101_pins.md
- docs/ashell.md
- samples/ButtonLEDs.js
- samples/ButtonLEDsAsync.js
- samples/RGB.js
- samples/TrafficLight.js
- samples/TwoButtons.js
- samples/arduino/basics/Blink.js
- samples/arduino/digital/Button.js
- samples/tests/ButtonEnable.js
- src/zjs_a101_pins.c
- tests/test-a101-pins.js
Also, rename the LEDs so the "bad" LED that breaks when SPI is enabled
is LED2 instead of LED0. Update samples to use the new names or switch
to using LED0 as the default.
Fixes #693.
> [docs] Document caveat about conflict between SPI and A101 LED

- samples/SensorBLEDemo.js
- src/zjs_buffer.c
- tests/test-buffer.js
A bug was introduced by recent negative numbers patch; high positive
numbers were being treated as negatives and limited to 0x7fffffff.
Also, clean up a couple other things from that patch: mistaken assumption
that we support noAssert flag in these calls, and a test that uses
unsupported calls. I left it in, commented out, because it seems
interesting once we do support those calls.
Fixes #851.
> [buffer] Fix bug in big-endian Buffer functions

- arc/src/main.c
strnlen is supported in NEWLIB and if we build ARC with
NEWLIB we no longer need our own strnlen()
> [arc] Remove strnlen and use strlen

- src/zjs_sensor.c
Also fixed bug where default NULL values are not set when no
arguments are passed in the constructor
> [sensor] Add missing timestamp

- samples/OcfClientUpdate.js
- src/zjs_ocf_client.c
Fixes #810
Client update was expecting the properties to be part of
the resource object, not resource.properties as it should
be.
> [ocf] Fix client resource property on update

- scripts/trlite
We were mistakenly leaving out most of the OCF code in our test builds.
> [trlite] Build OCF client/server code, not just common

- src/zjs_event.c
Fixes #917
If emit is called on an event object that has no events it
would print an error message. This was not really an "error",
just a message.
> [events] Changed ERR_PRINT to DBG_PRINT in trigger event

- modules/GenericSensor.js
> [tests] Add sensor.timestamp in GenericSensor module

- src/zjs_ocf_client.c
> [ocf] Improve get/platform info on client side

- src/zjs_ble.c
- src/zjs_buffer.c
- src/zjs_buffer.h
- src/zjs_dgram.c
- src/zjs_i2c.c
- src/zjs_uart.c
Also, return the handle in a new out param to simplify detecting the
error case from the caller.
Addresses a request in #916.
> [buffer] Return an error when out of memory in zjs_buffer_create

- src/zjs_buffer.c
> [buffer] Return buffer as out parameter to zjs_buffer_create()

- Makefile
One of the previous patch broke the Makefile so that
jerryscript flags are not appended to EXT_JERRY_FLAGS,
which caused final ROM size to go up significantly.
Fixes #901
> [build] Fix makefile bug that EXT_JERRY_FLAGS are ignored

- src/ashell/file-utils.c
- src/ashell/shell-state.c
Also added newline to all the error strings to keep the terminal
output clean.
Fixes #799
> [ashell] All ashell commands check if the file exists

- Makefile
- Makefile.zephyr
Instead of replacing the same libjerry-core.a with a different version
depending on snapshot vs. parser build, maintain both with different
filenames. Then we don't have to rebuild JerryScript just because we
switched between those two types of builds, and don't need the snapshot
last_build file and related dangers of inconsistency.
> [build] Maintain both snapshot and parser versions of JrS library

- src/zjs_buffer.c
> [buffer] Check for NULL return buffer pointers in create func

- README.md
Without this, `ct-ng build` will fail
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
> Adds CT_CC_GCC_STATIC_LIBSTDCXX=n to custom .config settings

- src/zjs_timers.c
Timeouts automatically get removed since they are a "once"
callback.
> [timers] Only remove interval timers in delete_timer()

- scripts/trlite
Running these buffer tests would have prevented two buffer issues from
slipping past us last week I think.
Also added several other tests that work on Linux.
> [trlite] Run more tests on Linux to catch buffer issues, etc.

- src/main.c
- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_buffer.c
- src/zjs_console.c
- src/zjs_dgram.c
- src/zjs_error.c
- src/zjs_event.c
- src/zjs_fs.c
- src/zjs_gpio.c
- src/zjs_grove_lcd.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_i2c.c
- src/zjs_modules.c
- src/zjs_performance.c
- src/zjs_promise.c
- src/zjs_pwm.c
- src/zjs_sensor.c
- src/zjs_test_promise.c
- src/zjs_timers.c
- src/zjs_uart.c
- src/zjs_unit_tests.c
- src/zjs_util.h
These simplify the boilerplate of declaring JavaScript to C binding
functions. The one downside is this hides the variable names that
are declared, so you're expected to know what those are.
> [utils] Add ZJS_DECL_FUNC and related macros

- Makefile
If you don't like this, you can export ROM=256 or whatever you like in
your shell. But whenver you test small samples that can fit in the
default 144 it makes more sense to do that because it will flash
faster (and also wear out the flash on the device less quickly).
> [build] ROM=144 default makes more sense to minimize flash times

- src/zjs_fs.c
Names like zjs_open and zjs_read were too generic.
Also, remove one unnecessary test for a null string already known to
be non-null.
> [fs] Add fs_ to functions in keeping with other modules

- fragments/zjs.conf.dev
If sensor is enabled, it will cause GPIO input to be disabled for
all pins.  Because GPIO is used more often than sensor, sensor is
being taken out of the default ashell configuration.  You can
enable sensor again simply by uncommenting it in the file.
> [ashell] Removing sensor from ashell default configuration

- docs/ashell.md
- src/Makefile.base
- src/ashell/Makefile
- src/ashell/comms-uart.c
- src/ashell/file-utils.c
- src/ashell/file-utils.h
- src/ashell/shell-state.c
- src/ashell/shell-state.h
- src/main.c
- src/zjs_util.h
Now ashell will run whatever JavaScript file is specified
in boot.cfg. Users can set which file to run on boot using
'cfg' in the ashell menu. ashell operates as usual even if
it starts up a program.
> [ashell] Boot JavaScript file specified by boot.cfg

- README.md
- docs/console.md
- samples/OcfSensorClient.js
**Doc fix and sample added:** #1012 #1010 
> Sync 0.3 docs fix and sample added

- modules/Assert.js
Naming the assert function accomplishes the same thing here.
> [assert] Remove arguments.callee usage, not allowed in strict mode

- scripts/analyze.sh
- src/zjs_gpio.c
- zjs.conf
I'm pretty sure this is no longer needed because building the module
is controlled by ZJS_GPIO but want to send out this canary before
changing all the modules. BUILD_MODULE_GPIO is still used in modules.c
and *pins.c to control a few sections though.
Also, fix a string in analyze and add a comment to the top of zjs.conf
describing how it is used, which I found along the way.
> [gpio] Remove BUILD_MODULE_GPIO ifdef around zjs_gpio.c file

- src/ashell/file-utils.c
- src/ashell/jerry-code.c
- src/zjs_modules.c
- src/zjs_modules.h
I was checking the length of the filename against the maximum
JS file length. Native modules can be longer and were failing
because of this.
> [ashell] Fixing using native modules with long names in ashell

- scripts/checkheaders
This package prevents some non-helpful errors from appearing like:
fatal error: sys/cdefs/h: no such file
Which might be hard to figure out, otherwise.
> [headers] Warn if libc6-dev-i386 package not installed

- docs/sensors.md
- samples/BMI160Accelerometer.js
- src/zjs_sensor.c
- tests/test-bmi160accelerometer.js
The includeGravity flag doesn't exists in the W3C spec as
the Accelerometer is split into LinearAccelerationSensor and
GravitySensor.
> [sensor] Remove gravity option in Accelerometer

- Makefile
- scripts/analyze.sh
- src/zjs_ble.c
Refactored BLE module to handle multiple connections,
Zephyr default to only 1 client connection, so added a config
to overwrite it to support up to 4 clients.
Also enabled CONFIG_BLUETOOTH_DEBUG_LOG in debug mode to get more
more useful output.
Fixes #984, #334
> [ble] Support multiple client connections (only up to 4 due to memory constraints)

- src/ashell/shell-state.c
If the board __TIMESTAMP__ is newer than the one in boot.cfg,
remove it.  This allows users to get their ashell build out of a
bad state should the javascript function they specified in boot.cfg
wedges the board on boot.
> [ashell] Remove boot.cfg if this is a newly flashed board

- Makefile
- scripts/analyze.sh
- src/Makefile.base
- src/sensors/Makefile.base
- src/sensors/zjs_sensor_accel.c
- src/sensors/zjs_sensor_accel.h
- src/sensors/zjs_sensor_gyro.c
- src/sensors/zjs_sensor_gyro.h
- src/sensors/zjs_sensor_light.c
- src/sensors/zjs_sensor_light.h
- src/sensors/zjs_sensor_temp.c
- src/sensors/zjs_sensor_temp.h
- src/zjs_sensor.c
- src/zjs_sensor.h
Instead of having all the different Sensor implementations
all exists in a single file, it's cleaner to break it out
into separate sub modules, which then can be loaded separately.
The sensor.c just implements the core sensor logic and will
have the individual sensors handle the data through callbacks.
> [sensor] Modularize sensor into separate submodules

- README.md
- scripts/analyze.sh
- analyze was missing a case statement.
- Zephyr BLE config options should be the same as A101
> [nRF52] Added experimental support for nRF52

- README.md
- docs/6lowpan-ble.md
- OCF was only mentioned but the setup was the same
for a 6lowpan device using Net/Dgram
> [docs] Updated 6lowpan docs to include Net/Dgram

- modules/GenericSensor.js
- samples/AmbientLight.js
- samples/BMI160Accelerometer.js
- samples/BMI160Gyroscope.js
- samples/BMI160Temperature.js
- src/zjs_sensor.c
Updating implementation and samples due to change of latest W3C spec
no longer has onstatechange.
> [sensor] Remove onstatechange event callback

- Makefile
- Makefile.linux
- scripts/trlite
- src/Makefile.base
- src/zjs_a101_pins.c
- src/zjs_gpio.c
- src/zjs_gpio_mock.c
- src/zjs_gpio_mock.h
- src/zjs_modules.c
- tests/test-gpio.js
This patchset adds a ZJS_GPIO_MOCK #ifdef that controls whether the GPIO module uses Zephyr APIs or replaces them with mock implementations. In the latter case, it also adds a gpio.mock === True to the JS API and a wire(pin1, pin2) function that lets you simulate a wire connection from a JS test.
This lets you do hardware-dependent testing like our test-gpio.js completely in software, while running every line of our GPIO module code w/o modification.
Warning: This contains some black magic. In particular, I substituted a jerry_value_t for an opaque struct device *. I can probably come up with a cleaner way to do that, but first wanted to just get this out there for comment to see whether it's completely insane to go down this path. :)
My biggest concern is that this roughly doubled the …
> Mock gpio module to run tests on Linux

- Makefile
Some of the analyze scripts should belong to the ARC, also adding -q to
suppress output of grep so it doesn't show up multiple times during
build
> [build] Fixed analyze for ARC

- arc/src/main.c
- fragments/zjs.conf.dev
- scripts/analyze.sh
- src/zjs_sensor.c
Polling mode is enabled by default when GPIO module is
enabled, instead of using triggers to monitor change events,
the ARC will poll the sensor data, this patch will allow
Ashell to have both GPIO and Sensor enabled.
> [sensor] Support polling mode for Ashell

- src/zjs_sensor.c
Fixes a previous patch that accidently call into JerryScript engine
from the IPM interrupt again since this is not safe.  Intead, store
state in the handle and query that instead.
> [sensor] Fix calling get_state calling into JerryScript from interrupt

- src/main.c
The semaphore change recently broke some things. This showed up for me
in samples/AlarmClock.js but also may be the root cause of part of
Timers were being checked first, then callbacks, so if for example a
GPIO input interrupt came that caused a callback, and that callback
set a timer, it still thought there were no timers. This fix may or
may not be sufficient, but it's probably not the best way to do it
and the problem should be considered more carefully.
> [main] Quick fix: Timer added in callback goes unnoticed

- Makefile
- README.md
- scripts/analyze.sh
- Added 'flash' target to make to support BOARD=nucleo_f411re
- Moved around analyze.sh lines for UART/FS for possible
support on other targets
- Added more info in README about supported boards and features
> [boards] New board support/docs

- docs/ashell.md
- src/ashell/comms-shell.c
- src/ashell/comms-shell.h
- src/ashell/comms-uart.c
- src/ashell/ihex-handler.c
- src/ashell/shell-state.c
Add ashell echo command to turn on/off printing JS transfer commands on the console. Also, update ashell docs to mention how to blacklist the device from ModemManager.
> [ashell] Add echo command to turn on/off printing commands on the console

- arc/src/main.c
- scripts/analyze.sh
- src/ashell/Makefile
- src/ashell/comms-uart.c
- src/ashell/file-utils.c
- src/ashell/ihex-handler.c
- src/zjs_aio.c
- src/zjs_callbacks.c
- src/zjs_timers.c
- src/zjs_util.c
The latest Zephyr has a work-around to use -O2 instead of -Os to build
the ARC so it does not need debug build for AIO to function properly.
Reverted previous fix to turn on debug build and rebased code on
new Zephyr tree.
> [build] Update latest Zephyr to remove debug fix for AIO

- src/ashell/comms-shell.c
- src/ashell/comms-uart.c
- src/ashell/comms-uart.h
- src/ashell/ihex-handler.c
- src/ashell/jerry-code.c
- src/ashell/jerry-code.h
- src/ashell/shell-state.c
This fixes the duplicate character issue on UART, removes a bunch
of unused strings, and functions that were redundant.
> [ashell] Fixing duplicate characters on UART

- src/zjs_fs.c
FS.truncate() will always fail since it doesn't check the wrong return
value from Zephyr
> [fs] Fix truncate check for wrong return value

- docs/ashell.md
Update ashell docs to mention generic udev rules which are compatible
on all Linux distros. We don't need to disable the modem manager when
there is a udev rule that prevents the modem manager interfering with
the device, so remove instructions that were added for disabling the
modem manager.
> [ashell] Update docs to mention generic udev rules for the WebUSB device

- src/ashell/comms-shell.c
- src/ashell/comms-shell.h
- src/ashell/shell-state.c
This disables the raw mode control/transfer messages in
the console when echo is off.
> [ashell] Disable raw mode control messages in the console

- docs/ble.md
- src/zjs_ble.c
- tests/test-ble.js
The issue is that the c callback is immediately removed
after the callback is signaled, and the main loop have not
serviced the callback yet.  We don't need to keep a separate
callback for each connection anyway, so instead use
a singal C callback for connect and disconnects.
Fixes #1088
> [BLE] Fixes disconnect callback not getting called

- arc/src/main.c
- src/zjs_sensor.c
There are two bugs in ashell, where we aren't checking
the polling flag correctly on ARC and we are not
stopping the ARC from sending sensor changes when you
stop the JS.  Also fixes bug where we are not cleaning
up the module properly in the cleanup() function.
Fixes #1029
> [sensor] Fix sensor cannot stop/start in IDE/Ashell

- src/ashell/comms-uart.c
Waits until a newline or 80 chars on stdout arrive before sending.
This seems to solve, or at least radically decrease likelihood,
of duplicated characters on redirected stdout.
> [ashell] Buffer stdout before sending on wire

- src/ashell/jerry-code.c
- src/zjs_modules.c
Also, improve parsing of require() by requiring parentheses, requiring
the string to be found within them, but allowing whitespace around them.
Note some of the remaining foibles with comments.
> [ashell] Fix add_requires to allow single as well as double quotes

- src/zjs_buffer.c
- src/zjs_i2c.c
> [general] Fix reversed order args from recent ZJS_DECL_FUNC patch

- src/zjs_buffer.c
- This prevents buffer from composing a string that could be used
to access hidden ZJS properties
> [buffer] Fix buffer.toString() to bail if there is 0xff in ascii

- docs/gpio.md
> [docs] Remove reference to openAsync in gpio docs

- README.md
Add more information and pointers on how to get started
with the Web IDE (inc. link to the video tutorial that was
posted on the Zephyr Project website).
Re-organize a bit the content and index to improve the flow
and readibility
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
> README.md: add more information about Web IDE

- samples/WebBluetoothDemo.js
- samples/WebBluetoothGroveLcdDemo.js
One of the variables needs to be renamed, since it
was actually causing a JS error.
Fixes #1215
> [ble] Fixed WebBluetooth demo fails on initial read

- docs/ashell.md
- src/ashell/webusb-handler.c
This defines device interface GUID in the extended properties
descriptor so that the Windows generic driver WinUSB will
be loaded automatically when the device is connected to the
host. This makes the installation process simple on Windows.
Also, we do not need to install the driver manually anymore, so
removing Zadig utility instructions from the docs.
> [webusb] Define device interface GUID

- arc/src/main.c
- arc/src/zjs_sensor_light_arc.json
The adc_read() on Zephyr has a latency of 100ms which causes
the AIO read to be very slow.  This patch now spawns a thread
that fetch ADC for any pins that are enabled so that
the main thread on ARC will just look up the fetched value.
> [aio] Fixed AIO read slow on ARC

- src/zjs_modules.c
> [modules] Fix bug where module string printed can be empty

- samples/SPI.js
If the MOSI / MISO pins are not connected, the print will fail
with the message SPI error: buffer has invalid ascii. To avoid
this, I'm changing it to print using HEX.
> [SPI] Changing the SPI example to print with hex instead of ascii

- Makefile
- arc/src/zjs_arc.json
- src/zjs_arduino_101.json
- src/zjs_ashell.json
- src/zjs_common.json
- src/zjs_frdm_k64f.json
- src/zjs_qemu_x86.json
This includes base configuration common to all platforms.
Fixes #1260.
> [analyze] Add zjs_common.json that always gets pulled in

- scripts/analyze
Currently if FORCE is provided, it analyze only looks at those
modules.  With the addition of FORCE=zjs_common.json this breaks
building with JS=samples/* as it only includes the common.json.
> [build] Fix for FORCE in analyze

- src/zjs_iotivity_constrained.json
- src/zjs_ocf_server.c
The problem is that iotivity-constrained didn't build with OC_DYNAMIC_ALLOCATION,
also added NULL checking to prevent segfault.
Fixes #1284
> [ocf] Fixed OCF random segfault on FRDM-K64F

- Makefile
- Makefile.linux
- src/zjs_callbacks.c
- src/zjs_common.h
- src/zjs_linux_port.h
- src/zjs_linux_ring_buffer.c
Disable ocf build and fixed linux build on MacOS.
Fixes #1290
> [build] Fix linux and QEMU build on Mac

- src/zjs_callbacks.c
- src/zjs_uart.json
The lock in signal_callback is not freeing before UART is
triggered.  This is causing UART to be locked out when it tries
to write.  Moving the unlock up fixes the issue.  Also adding a
needed item to the zjs_uart.json file.
> [uart] Fix for 1279 UART not working

- arc/src/arc_aio.c
Fix the bug where both AIO pin values and last changed values
are updated at the same time, and so it was no longer
sending onchange events
Fixes #1281
> [aio] Fixed onchange not called

- docs/pme.md
The number of committed neurons can be 0-128.
Fixes #1244
> [doc] Fix typo in PME doc

- scripts/trlite
> [trlite] Add fs to k64f tests so we catch build regressions

- Makefile
The 0.9.1 SDK still has upstream bug #2363 not fixed, so
this work-around patches our build to build with -O2 on ARC
images so it fixes the bug with AIO not booting.
> [build] Work-around fix for Zephyr SDK bug on AIO

- src/zjs_modules.c
- src/zjs_util.c
- src/zjs_util.h
This provides a method to print all the memory left after the
module cleanup methods have been called.  It will provide an easy
way to spot memory leaks.  You can use this method to print at any
time, but currently it will only be called after module cleanup.
> [tools] TRACE=on will now print all memory left after cleanup

- samples/websockets/WebSocketServer.js
- samples/websockets/WebSocketServer4.js
After a websocket had been closed, there still was a pending
timeout to send more data. This clears that timeout if a
close event is triggered.
Fixes #1372
> [websockets] Fix fault when closing websocket

- src/zjs_callbacks.c
If someone callback id of exactly cb_size, this would cause an
invalid offset into cb_map, at least on the boundary of a new chunk
of callbacks.
> [callbacks] Fix possible overflow of callback ID

- arc/src/zjs_ashell_arc.json
- arc/src/zjs_grove_lcd_arc.json
This patch fixes the bug where Ashell/IDE didn't include
the ARC build for Grove LCD.
Fixes #1357
> [grove_lcd] Fix Grove LCD not working in IDE

- arc/src/arc_pme.c
- docs/pme.md
- samples/PME.js
- src/zjs_ipm.h
- src/zjs_pme.c
- tests/test-pme.js
The setNeuronContext() and getNeuronContext() APIs are internal APIs
that should only be called in save/restore modes, applications
should not be calling this function directly, but instead
use the saveNeurons() and restoreNeurons() instead.
Fixes #1245, #1246
> [pme] Drop neuron context APIs as it's internal-only

- src/zjs_uart.c
Due to ZEP-2074, the Arduino 101 is limited to sending 4 bytes of data at a time via CDC_ACM.  This fix addresses that limitation.
> [uart] Fix for issue #1345, only 4 bytes sent to UART

- src/zjs_modules.c
Linux instance can now be closed from JS with process.exit()
Fixes #1387
> [process] Add process.exit() for Linux build

- scripts/analyze
> [analzye] Ensure dlist is composed only of module names

- arc/src/arc_curie_pme.c
Configure will now call the helper method to set both modes instead of
writing directory to the register, this fixed an issue where app
cannot reconfigurate classification mode once it is set.
Fixes #1254
> [pme] Change how configure set classfication and distance

- src/zjs_ocf.json
The OCF was not able to send packets over BLE 6lowpan
consistently and segfaulting, this patch increase
the data size to help improve stability.
Fixes #1255, #1408, #1415
> [ocf] Improved OCF stability over 6lowpan

- src/zjs_net.c
If 2+ clients connected, if either disconnected they would both be
disconnected by the server.
> [net] Fix issue with multiple client connections

- src/zjs_arduino_101.json
- src/zjs_ble.json
The callstack of 2k is causing segfault in BLE
when it starts physical web advertisting, increasing
it to 4k fixes the segfault.
Fixes #1421
> [general] Increase call stack size to improve BLE stability

- tests/test-tcp6-server.js
Before: When sever listening without callback function, will not trigger `listen` event.
Now: Trigger `listen` event.
Fixed #1425 
> [tests] Update test-tcp6-server.js for bug fix

- arc/src/arc_aio.c
The patch of spawning another thread to read cached
values is not needed as it has a regression issue and
there's a better way to solve the slow read of ADC.
Fixes #1329
> [aio] Revert previous AIO read patch

- Makefile.linux
- scripts/checkheaders
- src/Makefile.base
- src/jerry-port/zjs_jerry_port.c
- src/main.c
- src/zjs_promise.json
- tools/Makefile.snapshot
Update JerryScript and use the new Promise jobqueue implementation
as it is now built-in to JerryScript, thus no longer need to
provide our own job queue, which hopefully fix some of the bugs.
> [promise] Use built-in JobQueue implementation

- src/zjs_event.c
This compares the null terminator of the event name string so that it
will no longer match prefix but only exact string match.
Thanks to Cui Yan for finding the bug and another proposed solution.
Fixes #1432
> [events] Stop matching on event prefix

- docs/net-config.md
- samples/TCPClient6.js
- src/zjs_net_config.c
- tests/test-tcp6-client.js
- tests/tools/test-tcp6-server.py
If the net-config module is included, the user needs to either set a
static IP address or use DHCP; no default address will be set. We could
potentially change this, but this requirement makes for better example
code because it's more realistic.
Added setStaticIP call to a sample and a test that needed it.
Fixes #1413
> [net-config] Update docs to require setting IP address

- src/zjs_buffer.c
- tests/test-fs.js
> [buffer] Fixed bug in .toString() where a NULL terminator was ignored

- arc/src/arc_sensor.c
- arc/src/arc_sensor.h
The poll frequency was declared as a static variable and
couldn't be set from a different src file, making it extern
so it could be set.
Fixes #1451
> [sensor] Fixed polling frequency not updated

- arc/src/arc_sensor.c
- docs/fs.md
- samples/FsAsync.js
- samples/FsSync.js
- src/zjs_fs.c
- tests/test-fs.js
We are not currently checking if the file exists when
calling FS.statSync() to create the Stats object, in which
case if the file doesn't exists, we should return a undefined
value, and the unit tests should also check if the value
is undefined.  Added a ToDo to properly fix this with adding
a FS.exist() api that can be used to check if the file exists,
and then return a valid FSStat object when the file is invalid
according the NodeJS spec.
Fixes #1205
> [fs] Fixed invalid FSstat object when file is deleted

- src/ashell/shell-state.c
The error is not a useful command and should be removed as
it is already removed from the help menu, this fixes
a potential lock up issue when used without passing an arugment
Fixes #1027
> [ashell] Removed error command from Ashell

- Makefile
> [build] Fix the make gdb command to use updated path to gdb

- samples/TCPClient6.js
Move connection options to a struct near the top of the file, with
the IP addresses and ports used called out. Add a print statement at
the top to identify the sample.
Also, change the server address from the link local address of James's
machine to the normal 2001:db8::2 address we use.
> [net] Clean up TCPClient6.js sample

- docs/ashell.md
- src/ashell/shell-state.c
Update the help display to match and add documentation for various
commands that weren't documented.
Also, remove mention of ihex transfer because we plan to eventually
remove it entirely, and it's not really useful to the user in ashell
mode.
Fixes #1195
> [docs] Update ashell docs to match current command set

- docs/spi.md
- samples/SPI.js
- src/zjs_spi.c
- src/zjs_spi.json
- tests/test-spi.js
The SPI interface in Zephyr seems to accept a different
input for the max_sys_freq when configuring the bus, on
the Arduino 101, it is expecting it to be the clock divider
and on the FRDM-K64F, it is expecting it to be the baud rate.
Also removes configs that are not needed as it is automatically
set by Zephyr when you turn on SPI.
> [spi] Fix incorrect spi speed bus set

- src/zjs_net_config.c
The logic was wrong so that it wouldn't work for IPv4, and the
config flag had a capitalization typo.
> [net-config] Fix two bugs in setStaticIP

- docs/ashell.md
- src/ashell/shell-state.c
Added ability to erase the flash in Ashell/IDE, this
will help fix corrupted files created on the file system.
Fixes #1193
> [ashell] Added command to erase flash file system

- docs/net-config.md
- src/main.c
- src/zjs_ble.c
- src/zjs_ble.h
- src/zjs_net_config.c
- src/zjs_net_config.h
The bug is that once bt_enable() is called, it's impossible to set
the BLE address, so we have to move bt_enable() to be called after
all modules and the JS is loaded, this guarantees that any API call to
setBleAddress will be called before bt_enable().
Also update documentation to reflect this change.
Fixes #1400
> [ble] Fixed not able to set BLE address

- src/zjs_ocf_client.c
- src/zjs_ocf_common.c
- src/zjs_ocf_encoder.h
Added support for decimal values and arrays for property values in
OCF responses, this fixes a issue where different array types will
have wrong value when encoded or missing proper encoding.  Also
fixed the client to properly re-create the JS object from decoded
reponses.
Fixes #1489
> [ocf] Fixed OCF encoding issues

- src/zjs_util.h
Also, wrap CHECK_REF_COUNT in DEBUG_BUILD ifdef so it doesn't find its
way into production.
> [util] Add documentation for ZJS_GET_HANDLE

- samples/TCPClient6.js
- src/zjs_net.c
- src/zjs_util.h
The function was returning an error immediately in the IPv4 case, if no
network context was set in the socket handle.
Fixes #1483, but then reveals another bus fault error on K64F.
> [net] Fix socket_connect to support IPv4 connections

- src/zjs_net_config.c
The default address was actually being set, but there
were other methods being called that have been moved
to the main file, and needed to be removed otherwise it caused
havoc.
> [net] Fix for #1507 - Default ble address

- src/zjs_i2c.c
It turns out i2c_read doesn't support passing a register address.
Using i2c_burst_read now instead, this fixes the issue.
> [i2c] Fix for #593

- README.md
nRF52:
- Buffer, Console, Event, Performance, Timers(E->X)
- GPIO, OCF(E->Not Supported)
- ADC, PWM, I2C, BLE, Dgram, Net, WebSocket(NT->Not Supported)
Arduino DUE:
- Buffer, Console, Event, Performance, Timers(E->X)
- ADC, PWM, GPIO, I2C, UART(NT->Not Supported)
K64F:
- UART(X-> Not Supported)
- WebSocket(NT->X)
ST F411RE:
- File System(X->Not Supported)
- ADC, PWM, GPIO, I2C, UART(NT->Not Supported)
> [doc] Supported modules update for nRF52 and DUE

- src/ashell/comms-shell.c
- src/ashell/jerry-code.c
- src/ashell/shell-state.c
- src/zjs_aio.c
- src/zjs_ble.c
- src/zjs_board.c
- src/zjs_buffer.c
- src/zjs_dgram.c
- src/zjs_fs.c
- src/zjs_modules.c
- src/zjs_net_config.c
- src/zjs_ocf_client.c
- src/zjs_ocf_common.c
- src/zjs_ocf_server.c
- src/zjs_pwm.c
- src/zjs_sensor.c
- src/zjs_unit_tests.c
- src/zjs_util.c
- src/zjs_util.h
- src/zjs_web_sockets.c
This is more readable and less vulnerable to logic inversion.
> [util] Add strequal macro to replace strcmp for equality tests

- src/zjs_iotivity_constrained.json
Legacy Contiki based IP stack has been removed in
Zephyr, so removing obsolete include paths.
> [ocf] Do not source contiki headers

- src/zjs_net_config.c
- src/zjs_net_config.json
A bug in Zephyr prevents this from working currently, but it has been
fixed in zephyrproject-rtos/zephyr#1284. This just enables DHCP for
platforms other than K64F. Also, a minor style/convention tweak.
Fixes #1488
> [net] Allow DHCP to work on A101 w/ ENC28J60

- src/zjs_spi.c
If the passed arg is a Buffer object, I don't want to have
ZVAL free the original reference when its done, because I don't
own it. Instead, create a local reference that gets freed.
> [SPI] Adding an acquire when using provided buffer

- src/zjs_web_sockets.c
Now websocket clients can properly receive a close message
> [websockets] Add 'close' opcode

- README.md
nRF52:
- Buffer, Console, Event, Performance, Timers(E->X)
- GPIO, OCF(E->Not Supported)
- ADC, PWM, I2C, BLE, Dgram, Net, WebSocket(NT->Not Supported)
Arduino DUE:
- Buffer, Console, Event, Performance, Timers(E->X)
- ADC, PWM, GPIO, I2C, UART(NT->Not Supported)
K64F:
- UART(X-> Not Supported)
- WebSocket(NT->X)
ST F411RE:
- File System(X->Not Supported)
- ADC, PWM, GPIO, I2C, UART(NT->Not Supported)
> [v0.4] Supported modules update for nRF52 and DUE

- src/zjs_fs.c
- src/zjs_net_config.c
Also, restore style of args declaration in another place where I had
just fixed the same issue; after reviewing all of them I see we use
spaces around the braces consistently.
> [general] Use sizeof(args) as safer than manual calculation

- samples/WebBluetoothGroveLcdDemo.js
- scripts/trlite
- src/zjs_ashell.json
- src/zjs_util.c
I'm afraid we've been concerned only with ASCII to date but getting
strings as UTF-8 should get us a lot closer to correct behavior in the
face of extended characters.
> [utils] Switch to the use the new UTF8 JrS string functions

- docs/ashell.md
- src/ashell/webusb-handler.c
Allowed origins header (GET_ALLOWED_ORIGINS) request has been
removed from the WebUSB specification, so removing the support
for the request.
> [webusb] Remove support for the allowed origins request

- .travis.yml
- src/zjs_iotivity_constrained.json
- src/zjs_ocf.json
- src/zjs_ocf_client.c
- src/zjs_ocf_common.h
- src/zjs_ocf_server.c
This updates iotivity-constrained to latest to support OCF 1.0 spec. I tested this and the communication between iotivity-constrained and iot-rest-api-server is working fine on Linux.
On Zephyr over BLE, we still need to adjust the TX, RX and DAT_BUF sizes since the /oic/res (resource discovery) response size has changed according to OCF 1.0 standard and it is too large with more information. 
I'm adding support for query-oriented resource discovery in REST API server so that we can do the resource discovery with specific 'rt' query option (e.g: /oic/res?rt=core-light) and that response size will fit into the buffers.
Fixes #1485
> [ocf] Update iotivity-constrained to latest

- src/zjs_callbacks.c
It's not safe to be locking / unlocking mutexes from an ISR but we
were doing that because zjs_signal_callback is intended to be called
by ISRs. This was causing a hang in UART module after more careful
locking was added recently.
Fixes #1541
> [uart] Protect ring buffer access in ISRs w/ irq_lock not mutex

- Makefile.linux
- src/main.c
- src/zjs_callbacks.c
- src/zjs_common.c
- src/zjs_common.h
- src/zjs_linux_port.h
- src/zjs_linux_time.c
- src/zjs_timers.c
- src/zjs_util.h
- src/zjs_zephyr_port.h
Timers currently used the main event loop to check if
the timer had expired. This change uses Zephyr's timer
callbacks to signal the JS function. The linux port
uses signals to do the same thing.
> [timers] Make timers completely async/event driven

- Makefile
- Makefile.linux
- README.md
- src/Makefile.base
- src/ashell/Makefile
- src/main.c
This adds to ability to enable debugger mode for linux builds running
on the same host system, you can then connect a remote client to it
to debug JavaScript applications.
> [debugger] Enable Jerry debugger support for Linux

- src/zjs_common.h
Using __FILE__ macro in non debug code is increasing the
image size depending on where the sources are built, so
this patch removes that macro from the non debug code.
Fixes #1550
> [utils] Do not include __FILE__ macro in non debug builds

- src/zjs_gpio_mock.c
- src/zjs_ocf_client.c
- src/zjs_ocf_common.c
- src/zjs_ocf_common.h
- src/zjs_ocf_encoder.h
- src/zjs_ocf_server.c
- src/zjs_util.c
- src/zjs_util.h
- src/zjs_web_sockets.c
Using some code from #1497, this further improves the object
encoding/decoding. Instead of doing 2 passes on the object
to encode, this just does one. Also added support for arrays
of objects.
> [ocf] Much better way to do object encoding/decoding

- src/zjs_callbacks.c
- src/zjs_timers.c
Currently when zjs_timers_cleanup gets called, not all of the memory
in the callbacks is getting freed.  The ring buffer isn't being
freed before the javascript ends.  This change forces all the
memory to be freed when zjs_remove_all_callbacks gets called.
> [callbacks] Fixing a memory leak for callbacks

- docs/ashell.md
Fixes #727 - Pins 10-13 can only be used as SPI on ashell
when using the A101.
> [docs] Updating ASHELL docs with note about SPI pins

- .travis.yml
- README.md
- scripts/analyze
- scripts/checkheaders
- scripts/trlite
- src/MODULES.md
- src/ashell/term-uart.c
- src/zjs_ashell.json
- src/zjs_ble.c
- src/zjs_ble.json
- src/zjs_dgram.c
- src/zjs_net.c
- src/zjs_net_l2_bluetooth.json
- src/zjs_ocf.json
- src/zjs_ocf_common.c
- src/zjs_web_sockets.c
Also, update iotivity-constrained to build with Zephyr 1.9.
In analyze, add expanding of shell variables used in zephyr_conf
JSON settings to work around an issue with the MBEDTLS_CFG_FILE.
Add a workaround to checkheaders to create a stub file for
generated_dts_board.h that is expected.
Decrease ROM size in trlite builds to allow for slight expansion
in ARC image build size. Also, drop 'fs' module from ashell/ide
builds so that they will fit in the new 255 KB allotted.
Follow rename of CONFIG_BLUETOOTH_* to CONFIG_BT_* in Zephyr.
Slightly reorganize Bluetooth service registration to match new
convention.
Work around some network macros that have gone away.
Fix references to sections.h that moved.
> [zephyr] Update to Zephyr 1.9.0

- src/zjs_web_sockets.c
If the node client did not specify any websocket subprotocols
to use, the server would crash if the acceptHandler was
defined in the server init object. This was due to the protocol
array not being initialized if no Sec-WebSocket-Protocol
tag was present in the accept packet.
This initially sets the protocol array to undefined, and if its
still undefined when the acceptHandler is called it initializes
it to an empty array.
> [websockets] Fix crash if no subprotocols were included

- tests/test-pwm.js
The recent timer patch made JS timers much more accurate.
The PWM test was relying on the old slow timers. Changing
the interval values to what they should actually be fixes
the test.
> [tests] Fix PWM test to use actual time values

- src/main.c
- src/zjs_ble.c
This fixes the issue where bluetooth doesn't work in Ashell,
since when running in Ashell, bt_enable() cannot be called until
the Bluetooth module is initialized.  This also fixes the error message
showing up when IDE is launched.
Fixes #1502
> [ble] Fixed ble in Ashell

- src/zjs_linux_time.c
The new linux timer port uses signals as callbacks for
timers. The signal API expects a greater than zero timeout
so in the zero timeout case we pass 1.
> [linux] Fix linux port to allow for a zero timeout

- src/zjs_callbacks.c
> [callbacks] Currently CB_FLUSH_ALL is just flushing the same id,

- Makefile
- src/main.c
- src/zjs_dgram.c
- src/zjs_net_config.c
- src/zjs_net_config.h
- src/zjs_net_l2_bluetooth.json
- src/zjs_ocf_common.c
- src/zjs_web_sockets.c
Zephyr 1.9 has renamed all _BLUETOOTH configs to _BT
Fixes #1598
> [ble] Updated Zephyr net config

- Makefile
- src/ashell/file-utils.c
- src/ashell/file-utils.h
- src/ashell/term-cmd.c
- src/main.c
If you building the IDE by passing IDE_GPIO_PIN to configure
the board to only boot into IDE mode only if a button press is detected
For example:
make ide IDE_GPIO_PIN=8
This will build the IDE so that if a button is connected to IO8
on the board using GPIO and it's holded down when the Arduino 101
is booting, it will then boot into ASHELL/IDE mode, otherwise
it will look for the boot.cfg file and boots the file.
> [ashell] Allow setting IDE_GPIO_PIN to enter IDE mode

- src/main.c
- src/zjs_net_l2_bluetooth.json
Zephyr IP over Bluetooth now uses net_app configs
for configuring 6lowpan, and net_app will by
default call bt_enable() when initilized, so
we also need to unset CONFIG_NET_APP_AUTO_INIT
so that we can call bt_enable()
Fixes #1599
> [bluetooth] Fixed IP over Bluetooth issues

- src/ashell/term-uart.c
Currently ashell boot doesn't work with javascript that has callbacks
or timers.  This is because once the boot.cfg JS gets called, it
goes into an infinite loop waiting for uart. Until it gets the
connection, it won't return.  This means the main loop doesn't get
control back, meaning callbacks are not processed.  This change
breaks the code up a bit so that it checks if the connection is ready
when uart_process gets called, if not try to connect.  If the
connection fails, just return and go through the main loop again.
Continue until a connection is made.
> [ashell] Fix for ashell boot

- Makefile.linux
- src/main.c
- src/zjs_common.c
- src/zjs_linux_port.h
- src/zjs_linux_time.c
- src/zjs_timers.c
- src/zjs_util.h
The new timer patch #1542 uses librt which doesn't build on MacOS,
this patch revert linux builds to previous old timer
implementation for compatibility and adds a FIXME for all the places
the patch was reverted.  We need to find a way to add a cross-platform
implementation for timers that will work on both Linux and MacOS.
Fixes #1579
>  [timers] Revert patch #1542 for linux timers

- src/zjs_callbacks.c
There's no check on callback id when calling zjs_remove_callback(),
this will cause a segfault when callback id has not been set or
has a negative value.
Fixes #1593
> [callback] Fixed crash when removing callback with id -1

- Makefile
Not sure if these are going to cause a problem, but apparently Zephyr
doesn't use LTO now so we're better off making things match I expect.
> [build] Disable LTO for JerryScript to prevent ar warnings

- scripts/trlite
We should turn this into a hard fail as soon as we get everything
working again: callbacks, event, gpio, promise, and timers tests
were all broken by PR #1542.
> [trlite] Add soft fail when Linux tests don't reach completion

- src/ashell/term-cmd.c
- src/ashell/term-uart.c
Currently when the JS is run before ternminal is started
and callbacks starts before it can get printed, thus
queuing up the message queue.  Moving it to be run
after terminal is started.
Fixes #1644
> [ashell] Boot cfg should start after terminal started

- README.md
Updated instructions with work-arounds when building on MacOS
with Zephyr 1.9.
Fixes #1631
> [build] Updated MacOS build instructions

- Makefile
- Makefile.linux
- scripts/analyze
- src/Makefile.base
- src/ashell/Makefile
- tools/Makefile.snapshot
If not specified, 'outdir' remains the default.
> [build] Allow outdir to be specified with O=

- Makefile.linux
This fixes build fails on MacOS Linux builds
> [build] Fixed Linux outdir include path on MacOS

- README.md
- src/ashell/term-webusb.c
Web IDE repo has been migrated from 01org to Intel,
so update the landing page url.
> [webusb] Update the Web IDE url

- src/zjs_gpio.c
With the full pin naming method, the first part is used as a device name
so we should check that it's actually a legitimate device name.
> [gpio] Check for bad gpio device

- samples/tests/GPIO-Inputs.js
- samples/tests/GPIO-Outputs.js
For F411RE, this demonstrates how there are a total of 41 external pins
that actually work as GPIOs. For K64F, basically none of the extra pins
actually work w/ the default Zephyr configuration, but may in the
future if we update pinmux settings.
> [gpio] Expand GPIO tests for k64f/f411re to cover all external pins

- Makefile
The Makefile is setting BLE_ADDR to "none" which
it should be none instead so it doesn't think it's
valid BLE address.
Fixes #1678
> [ble] Fixed ble addr set default addr to "none"

- scripts/trlite
- src/main.c
- src/zjs_modules.c
- src/zjs_script.c
- src/zjs_script.h
- tools/snapshot.c
Linux requires the module object be returned to work.
Fixes #1687
> [modules] Fix to allow linux to load JS modules

- samples/tests/GPIO-Inputs.js
- samples/tests/GPIO-Outputs.js
This lets it succeed on A101 where certain pins can't be opened with
the default configuration.
Fixes #1690
> [samples] Fix GPIO-Outputs.js sample to handle open failures

- modules/ST7735.js
- samples/SPI_Screen.js
- src/zjs_gfx.c
New mode will draw pixels as it goes rather than saving them up.
This method uses far less RAM and is better suited for the A101.
Boards with more RAM can now take advantage of the flush mode
which draws far faster.
> [gfx] Fixing bugs and adding new drawImmediate mode

- CMakeLists.txt
- arc/CMakeLists.txt
Zephyr 1.10 requires CMake 3.8.2. For some actively used Linux distros
(e.g. Ubuntu 16.04), that version is not in repositories, and users
have to do extra legwork to install it. Then Zephyr.js pushes it even
higher. Try to use the value consisten with what Zephyr uses instead.
> [build] Downgrade cmake version check to 3.8.2

- Makefile
Update Makefile to support olimex_stm32_e407 and 96b_carbon boards using dfu mode.
a101: `make dfu` or `make dfu BOARD=arduino_101`
olimex_stm32_e407: `make dfu BOARD=olimex_stm32_e407`
96b_carbon: `make dfu BOARD=96b_carbon`
> [build] Update Makefile to support olimex_stm32_e407 and 96b_carbon

- README.md
Support more x86 and arm boards:
- tinyTILE
- ST STM32F4DISCOVERY
- OLIMEX STM32 E407
- 96Boards Carbon
> [readme] Update support modules for more boards

- README.md
The ZJS cmake instructions were wrong (and did not seem to work)
for ZJS. Updated the the same steps that zephyr uses. These
steps are also much easier and do not require actually building
cmake.
> docs: Fix readme to reflect zephyr docs for cmake

- src/zjs_ashell.json
- src/zjs_ashell_ide.json
Including this webusb_serial.c file with the ashell CLI causes
it to never get events, which means it hangs and waits forever
after the first print.  Moving the file to where it belongs.
> [ashell] Fix broken ashell CLI

- Makefile
Currently if you want to change the ROM / RAM size for an Arduino 101 build you have to do either make clean or make pristine.  This change fixes it so that if either value changes since the last build, it will rebuild to update the values.
> [build] Making changes needed to rebuild when ROM / RAM changes

- scripts/trlite
With patches from 2017 still pending, it doesn't make sense to break the
build when they get merged. Plus the error always annoyed everyone,
probably better to do this as a git commit hook.
> [trlite] Only warn on failure to update copyright year

- cmake/zjs.cmake
> [bluetooth] Fix BLE_ADDR is not set correctly in net-config

- README.md
Also, clarify that net-tools scripts should be run from inside that
directory since loop-slip-tap.sh looks for tunslip6 there.
Also, fix that sudo is not needed for loop-socat.sh but is for
loop-slip-tap.sh.
> [readme] Add info about libpcap-dev dependency for QEMU networking

- Makefile
- cmake/zjs.cmake
- scripts/trlite
This fixes the issue that Newlib is not being built with float printing
support when PRINT_FLOAT=on is passed to the command line.
> [build] Fixed build parameter PRINT_FLOAT not working

- .travis.yml
GCC5 should only be needed on Ubuntu 14.04 builds, not MacOS
since it uses clang.
> [build] Fix incorrect GCC version set for Mac builds on Travis

- cmake/zjs.cmake
Fixes regression bug that if no BLE_ADDR is set, "none" will
be passed to build instead causing an error.
Fixes #1754
> [ble] Fixed default ble set to "none"

- src/main.c
> [linux] Fix segfault when running jslinux with no args

- src/zjs_arduino_101.json
- src/zjs_common.json
- src/zjs_frdm_k64f.json
- src/zjs_net_l2.json
- src/zjs_net_l2_bluetooth.json
- src/zjs_net_l2_ethernet.json
- src/zjs_ocf.json
Add additional target configs for ARM boards so that apps that
require BLE or networking support.
> [build] Add support for 96b_carbon and olimex_stm32_e407

- README.md
- docs/boards/summary.md
New doc page compares basic stats about the boards we've tested on.
Also, update README to point to this doc page and shrink module
support table size.
> [docs] Add doc on tested board summary info, update readme

- src/zjs_net_config.c
The function was already a hack by hard-coding unicast[0] but this
does make it worse; it will take some investigation to learn how to
properly determine how many addresses are valid, but this should
work for now as a stop-gap.
Fixes #1774
> [netcfg] Skip link local address in zjs_net_config_get_ip

- Makefile
- arc/CMakeLists.txt
This will be a work-around to manually set the build
flag from -Os to -O2 until patch is merged into Zephyr
upstream.
Fixes #1367
> [arc] Set build optimization flag to -Os

- cmake/zjs.cmake
This setting was used previously to include
$(ZEPHYR_BASE)/samples/net/common/Makefile.ipstack, but switching
to CMake no longer requires this.
> [build] Removed unused NETWORK_BUILD

- samples/websockets/NodeWebSocketClient.js
- samples/websockets/NodeWebSocketClient4.js
Node.js automatically returns a pong when it gets a ping,
calling ws.pong causes two to be sent to the webserver.
> [ws] Removing unneeded pong

- src/zjs_net.c
Also, replace some magic numbers with constant from Zephyr for maximum
number of characters in an IP address string.
> [net] Call net_addr_ntop with correct arguments

- src/zjs_event.c
Only one event callback was supposed to be created, but the line was
moved to zjs_make_emitter so that it was created for each new emitter
object. For tests that close and open sockets repeatedly, for example,
this eventually caused the system to run out of memory.
Fixes #1737
> [events] Fix mem leak of overwriting callback id

- src/zjs_aio.c
- src/zjs_gpio.c
- src/zjs_pwm.c
Since the native pointer struct held a reference to the pin object,
neither would ever get freed.
Fixes #1363
> [gpio] Fix memory leak through unnecessary acquire

- scripts/analyze
Previously the main code execution path weaved its way between
function definitions. Change it so that we now have a main() function.
Also:
* Sort the imports alphabetically.
* Separate top-level functions by two blank lines per PEP8.
Signed-off-by: John L. Villalovos <john@sodarock.com>
> scripts/analyze: Use a main() function

- src/zjs_i2c_handler.c
The current I2C configure function uses a deprecated I2C struct,
with Zephyr 1.10, this is no longer valid and needs to updated
to use new type.
Fixes #1807
> [i2c] Update I2C configure type

- scripts/zjsbanner
On macOS builds python3 is installed in /usr/local/bin/python3 instead
of /usr/bin/python3 (which is where it is on Linux systems).
Use /usr/bin/env as it will find python3 if it is in the path.
Signed-off-by: John L. Villalovos <john@sodarock.com>
> Use "#!/usr/bin/env python3" for zjsbanner

- Makefile
- cmake/zjs_linux.cmake
- scripts/README
- scripts/analyze
* Use the argparse library for the argument parsing. Some of the
reasons this is an improvement are:
* Improved experience for the user as help messages are provided.
* It is easier to check argument values in the code this way.
* Arguments become self documenting, previously the usage()
function did not describe the "RESTRICT" and "V" options. By
using argparse every argument that is accepted will be shown
in --help.
* Updated two callers of analyze (Makefile & cmake/zjs_linux.cmake)
to use the new argument style.
* Changed 'outdir' to no longer be a global variable.
* Added a description of what the analyze program does to the help.  Now
if the user does:
$ scripts/analyze --help
They will see:
usage: analyze [-h] --board BOARD_NAME --json-dir DIR [--prjconf FILE]
[--cmakefile FILE] …
> Use the argparse library for command line argument parsing

- scripts/trlite
The macOS uses bash 3.x and the '-v' test command is unknown and we
see the error "[: -v: unary operator expected".
Change test to use '-z' to resolve this issue.
> Fix error: "[: -v: unary operator expected" in macOS build

- scripts/analyze
In commit 490ff661a54944456145b060d179c34a8f19101e the args.verbose
parameter was changed to an integer value but the comparison was still
using a string comparison.
Change it to compare with an integer value so that --verbose=1 works
and will print extra output.
Signed-off-by: John L. Villalovos <john@sodarock.com>
> [build] analyze: Change args.verbose comparison to integer

- Makefile
If project's sources are not cloned recursively,
or updated manualy using:
git submodule update --init --recursive
Dependencies modules will be fetched by GNU make.
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
> Update git modules recursively if needed

- src/zjs_ashell.json
This allows random() to be used in Ashell/IDE.
Fixes #1834
> [math] Add MathStubs to ashell build

- docs/sensors.md
- modules/GenericSensor.js
- samples/AmbientLight.js
- samples/BMI160Accelerometer.js
- samples/BMI160Gyroscope.js
- samples/BMI160Temperature.js
- samples/FXOS8700Accelerometer.js
- samples/FXOS8700Magnetometer.js
- samples/SensorBLEDemo.js
- src/zjs_sensor.c
- src/zjs_sensor_board_k64f.c
In the latest W3C spec, onchange event handler has been renamed to
onreading, and the state property is no longer exposed in the sensor
object.
Fixes #1829
> [sensor] Implements new W3C Generic Sensor API

- src/zjs_console.c
The ZVAL_MUTABLE string was not initialized to a jerry_value_t
when the function returns, the auto-release mechanism will
will segfault.
Fixes #1858
> [console] Fixed console print segfault on arrays

- src/zjs_ble.c
This was caused by the bt_uuid struct was not properly allocated
memory to store the bits.
Fixes #1869
> [ble] Fixed regression the UUIDs were not found

- src/ashell/jerry-code.c
- src/jerry-port/zjs_jerry_port.c
- src/main.c
- src/sensors/zjs_sensor_accel.c
- src/sensors/zjs_sensor_gyro.c
- src/sensors/zjs_sensor_light.c
- src/sensors/zjs_sensor_magn.c
- src/sensors/zjs_sensor_temp.c
- src/zjs_aio_a101.c
- src/zjs_ble.c
- src/zjs_callbacks.c
- src/zjs_event.c
- src/zjs_gfx.c
- src/zjs_grove_lcd_ipm.c
- src/zjs_modules.c
- src/zjs_sensor.c
- src/zjs_util.c
- tools/snapshot.c
> [jerryscript] Rebase to latest JerryScript

- src/main.c
- src/zjs_modules.c
- tools/snapshot.c
JerryScript updated the generate_snapshot API to return
a jerry_value instead of the size, so if you directly
use the size returned, it will be incorrect.
Fixes #1888
> [snapshot] Fixed incorrect snapshot size

- docs/grove_lcd.md
- docs/web-socket.md
- docs/webusb.md
For grove_lcd, the single blank line caused all of the links to be double-spaced.
For web-socket, I noticed that the actual C code was passing around the OptionsObject, which existed in some previous version of the docs, so I reinstated it.
For webusb, well, that was just one I missed; it isn't any different than all of the rest.
> Fixed small things on grove and web-socket and redid webusb, which I somehow missed on the first go around.
