intel/zephyr.js

README.md

[README] Verified http cloning works now, remove note

---

tests/test-timers.js

TOTAL: 8 of 8 passed
Signed-off-by: Cui, Yan <yanx.cui@intel.com>

[Tests] Add tests for Timers

---

tests/test-buffer.js
tests/test-eval.js

[Tests] Use expectThrow() in buffer and eval tests

---

Makefile

[build] Fixed MALLOC=heap broken build

---

src/zjs_common.h
src/zjs_timers.c
src/zjs_util.c

[debugging] Print elapsed time since start with DBG_PRINT/ERR_PRINT

---

src/zjs_callbacks.c

[callbacks] Fixed callback size increment

---

src/zjs_callbacks.c

[callbacks] acquire 'this' in callback module to fix bug

---

src/zjs_pool.c
src/zjs_pool.h

[pool] Added pool cleanup function

---

arc/src/main.c
samples/WebBluetoothDemo.js
samples/WebBluetoothGroveLcdDemo.js

It seems that the temperature value change update is causing random
update issue and dropped connection, changed the demo code to
only send updates if a value change is detected.
Also increase the interval between updates to a minimum of 2sec.

[Demo] Improve BLE demo stability

---

src/zjs_ble.c

[BLE] Change BLE to use zjs callback API

---

samples/I2CBMP280.js

This is a sample javascript program that uses both the BMP280 and the Grove LCD.  Both sensors work off the same I2C bus.  The BMP280 reads the temperature while the Grove LCD prints it.  The Grove LCD also changes to red as it gets warmer and blue as it gets cooler.  There is also a (+) or (-) indicating if the temp has gone up or down since the last read.

[Sample] Adding a sample program for BMP280

---

Makefile
docs/API.md
docs/uart.md
samples/UART.js
scripts/analyze.sh
scripts/convert.sh
src/Makefile.base
src/zjs_buffer.c
src/zjs_callbacks.c
src/zjs_event.c
src/zjs_modules.c
src/zjs_promise.c
src/zjs_uart.c
src/zjs_uart.h

- Fixed 'then' in callbacks by acquiring the value. Without this
promises did not work correctly if an object other than
undefined was used.

[UART] UART implementation

---

src/zjs_callbacks.c

[callbacks] Removed duplicate line of code from bad merge conflict

---

docs/ashell.md

Updating ashell doc file to be more complete.

[docs] Updating ashell doc file

---

tests/test-aio.js
tests/test-buffer-rw.js
tests/test-buffer.js
tests/test-eval.js
tests/test-timers.js

[Tests] Update print to console.log instead

---

samples/BLE.js
samples/tests/BufferMemory.js
samples/tests/ButtonEnable.js
samples/tests/Events.js

[console.log] Fixed all JS files to use console.log

---

.travis.yml
samples/TrafficLight.js

[travis] Add TrafficLight, I2C, and WebBT samples as standard builds

---

.travis.yml
Makefile

[travis/build] Fixed travis linux build

---

docs/timers.md

Fix a blank page in timers.md file.

[docs] Updating timers.md doc file

---

NOTICES

Signed-off-by: Geoff Gustafson geoff@linux.intel.com

[general] Add NOTICES file highlighting implicit usage of newlib

---

src/ashell/jerry-code.c
src/zjs_aio.c
src/zjs_buffer.c
src/zjs_console.c
src/zjs_gpio.c
src/zjs_ipm.c
src/zjs_k64f_pins.c
src/zjs_modules.c
src/zjs_timers.c

Merge in the last couple changes that had made it into devel, into master. Then we'll abandon devel branch and commit directly to master again as the main development branch.

End of devel

---

docs/ble.md

This updates the API documentation for RSSI api and also added
a section for decribing client requirements and setup that's required
to test the BLE samples.

[Documentation] Updated BLE API documentation and setup instructions

---

samples/Console.js
samples/tests/Console.js
src/zjs_console.c

[console] Fixed console.log/error to conform to Node.js better

---

tests/test-pwm.js

Fixed whitespace issues. Two test failures on A101 are by design but will
be addressed with redesign relatively soon.

[Tests] Add tests for PWM APIs

---

.gitmodules
Makefile
deps/.gitignore
deps/repos.txt

[submodules] Use git submodules

---

samples/UART.js

Also, add some comments in the same format as other samples.
Signed-off-by: Geoff Gustafson geoff@linux.intel.com

[uart] Update UART sample output w/ carriage returns

---

samples/tests/Console.js
src/Makefile.base
src/zjs_console.c

[console] Print bools and fixed float printing

---

src/zjs_event.c
src/zjs_promise.c
src/zjs_uart.c

[fixup] fixed promises/events to work with ring buffer change

---

tests/test-gpio.js

[Tests] Update test-gpio.js for bug fix

---

Makefile

[Makefile] Fix the debug and gdb targets for debugging A101

---

tests/test-k64f-pins.js

[Tests] Add tests for K64F-Pins API

---

src/zjs_console.c

Fix to console.log

---

Makefile.zephyr
src/zjs_util.h

[build] fixed build break from missing ZJS_PRINT and QEMU socket code

---

scripts/convert.sh

[build] Fixed convert.sh to work if uglify is not installed

---

Makefile

[makefile] Make analyze/generate targets dependent on JS file existing

---

deps/.gitignore

[cleanup] Remove old .gitignore file in deps

---

src/zjs_callbacks.c
src/zjs_event.c

Events now return this to allow chaining.
This is a re-based and slightly modified version of #340 by Gabriel Schulhof

[callbacks] Return this from some methods to support chaining

---

src/main.c
src/zjs_script.c
src/zjs_script.h

[linux] Fixed segfault if invalid script file is passed in

---

.travis.yml

[travis] Enable IRC notifications of commit build status

---

.travis.yml

[travis] Reduce VMs used to two in an effort to speed up builds

---

src/zjs_unit_tests.c
src/zjs_util.c
src/zjs_util.h

This should be rebased after #425 goes in.
I'm not really sure if this is a good idea, but it was a fun one. Hopefully if we don't use it, it won't actually take up any space.

Compress ints

---

tests/test-pwm.js

[Tests] Update test-pwm.js for bug fix

---

docs/grove_lcd.md

[docs] Update grove_lcd.md

---

.travis.yml

[travis] Fixed travis linux tests to use proper exe

---

tests/test-a101-pins.js
tests/test-gpio.js
tests/test-k64f-pins.js
tests/test-pwm.js

These tests should be tested in zjs-0.1

[tests] Sync tests from master

---

tests/test-grovelcd.js

[Tests] Add tests for GroveLCD APIs

---

src/zjs_gpio.c

For this allow "pin" property passed to open() to take a string value
like "GPIO_1.21". Part before the dot is Zphyr native GPIO port device
name, after the dot - ping number within that port. This notation allows
to access GPIO of any board supported by Zephyr kernel, without any
additional patching and modules on Zephyr.js (additional convenience
modules *can* be added for more boards, the main point is that they
are now optional (later perhaps implements in JS code)).

[GPIO] Allow to work with Zephyr-native GPIO port and pins.

---

scripts/memorystats

[bugfix] Fix for memorystats

---

tests/test-i2c.js

TOTAL: 10 of 12 passed
Issue: https://github.com/01org/zephyr.js/issues/477

[tests] Add tests for I2C APIs

---

tests/test-ble.js

[tests] Add tests for BLE APIs

---

tests/test-ble.js
tests/test-grovelcd-cursor-manual.js
tests/test-grovelcd-ds-manual.js
tests/test-grovelcd-rgb-manual.js
tests/test-grovelcd.js
tests/test-i2c.js

These tests for 0.1 features have been submitted in master, sync them to zjs-0.1 branch.

[tests] Sync 0.1 tests of BLE/I2C/Grove LCD from master

---

modules/GroveLCD.js
samples/I2C.js
samples/I2CBMP280.js

[bugfix] Fixes issue with I2C demos not showing backlight

---

samples/tests/Console.js
src/zjs_console.c

Also, improve handling of spaces between arguments, and improve Console.js
test to be more thorough and clean up output.

[console] Support printing arrays, functions, null, undefined

---

README.md

[docs] Update udev rules

---

scripts/memorystats

Now memory stats can compare your current branch to a previous
one, showing you the change in ROM/RAM usage.

[script] New compare feature for memorystats

---

samples/arduino/starterkit/Spaceship2.js

Stop using the event.value because it's unreliable because of button
bounce issues. Also, double edge interrupts are better used when the
same action will be triggered either way. Here a better approach to
make sure the lasers get turned off eventually is to check the button
status repeatedly in a timer. This makes it more like Spaceship.js
but at least the lasers will turn on immediately, rather than syncing
to 250ms timer, which is important when you're leading a TIE fighter.

[samples] Fix Spaceship2.js timer bug

---

scripts/analyze.sh
src/Makefile.base

There were a couple modules that got left off, such as Buffer and
Timers.  Now these can be built adding them to the config file.

[modules] Updating analyze.sh to check for all forced modules

---

modules/Assert.js
tests/test-uart.js

[tests] Add tests for UART APIs

---

tests/test-timers.js

[tests] Update test-timer.js for testpoint added

---

tests/test-grovelcd.js

[tests] Update test-grovelcd for repetition deleted

---

Makefile

[makefile] Fix make clean and stop hardcoding deps/ as the path

---

scripts/analyze.sh

[analyze] Fix bug that broke Buffer detection

---

src/ashell/jerry-code.c
src/main.c
src/zjs_modules.c

[modules] Move fixed module init/cleanup to zjs_modules.c

---

Makefile

Also, setup and clean targets no longer do update automatically; that
must be run explicitly. This allows you to build with custom submodule
trees without it checking out the intended version over the top.

[makefile] Remove last build tracking and clean pre-action

---

tests/test-uart.js

[tests] Update test-uart.js for bug fix

---

Makefile.linux
src/zjs_linux_time.c

This is the final fix for #513

[OSX] make linux build to work also on Mac/OSX

---

src/zjs_event.c

- Fixed return values of some functions to be correct and consistent
- Changed DBG_PRINT's to ERR_PRINT's when appropriate

[events] Fixed and updated event module

---

README.md

[README] Documented the linux target

---

arc/src/Makefile.base

[arc] Fix build broken by creation of zjs_common.c

---

docs/API.md
docs/events.md

[docs] Event API documentation

---

src/zjs_callbacks.c

[bugfix] Fix for issue 562

---

samples/I2CBMP280.js
src/zjs_ble.c
src/zjs_util.c

[util] Fix bug in size returned by zjs_copy_jstring

---

Makefile.zephyr
scripts/analyze.sh
src/ashell/main-zephyr.c
src/zjs_event.c
src/zjs_ocf_client.c
src/zjs_ocf_common.c
src/zjs_ocf_server.c
src/zjs_promise.c

[OCF] Updated Zephyr and iotivity-constrained to latest

---

src/zjs_aio.c

[aio] Remove unused struct fields and consolidate functions

---

tests/test-event.js

[tests] Add tests for Event APIs

---

tests/test-aio.js
tests/test-ble.js
tests/test-gpio.js

Recode test-aio.js for bug fix and realloc pins for automated testing.
Defined Lines:
modules | wire | to
---- | ---- | ----
aio | IO4 | A0
pwm | IO2 | IO3
gpio | IO7 | IO8

[tests] Realloc pins for automated testing

---

tests/test-uart-read-manual.js
tests/test-uart.js

[uart] Recode test-uart.js into manual and automatic

---

src/zjs_buffer.c

[buffer] Use native handle to track buffers and eliminate list

---

Makefile
Makefile.zephyr

[build] Fixed non-OCF QEMU builds

---

scripts/leakfinder
src/main.c
src/zjs_ipm.c

Minor fix - removing uneeded jerry_release from ipm

[script] Creating leakfinder script and minor fix

---

docs/API.md
docs/console.md
src/zjs_console.c
src/zjs_error.h

[console] Added console API documentation, and fixed a minor bug.

---

src/zjs_console.h

[console] Fix warning in header file and add documentation

---

README.md

[docs] Better Linux documentation of tests (what works and does not)

---

modules/GenericSensor.js
tests/test-accelerometer.js
tests/test-ambientlight.js
tests/test-gyroscope.js

Result:
Num | pass | total
---- | ---- | ----
single | 12 | 14
all | 36 | 42
Issue: [#595](https://github.com/01org/zephyr.js/issues/595)
Issue: [#596](https://github.com/01org/zephyr.js/issues/596)

[tests] Add tests for Sensor API

---

modules/GenericSensor.js
tests/test-accelerometer.js
tests/test-ambientlight.js
tests/test-event.js
tests/test-gyroscope.js
tests/test-uart-read-manual.js
tests/test-uart.js

[tests] Sync 0.2 tests of Sensor/Uart/Event from master

---

src/zjs_error.c
src/zjs_error.h

Also, alphabetize the error lists and add a comment to prevent this kind
of problem in the future.

[error] Add AssertionError to error_types array to fix bug

---

src/zjs_console.c

Rewrite print_value to work in terms of a new value2str so that it can
be called independently when we need a string and not direct output.

[console] Improve assert to print all values and throw errors

---

src/zjs_callbacks.c

- There is still not support for handling these errors,
but at least printing them is better than nothing

[callbacks] Print errors for our own callbacks

---

tests/test-event.js

[tests] Remove abnormal test point cannot be catched

---

src/zjs_callbacks.c
src/zjs_linux_ring_buffer.c

[ringbuf] Fixed linux ring buffer to not fill up after some time

---

Makefile
Makefile.linux
samples/I2C.js
src/zjs_buffer.c
tests/test-event.js

[build] Fix Linux clean build

---

src/zjs_modules.c
src/zjs_script.c

[linux] Support JS module loading on Linux

---

docs/ashell.md

[docs] Updating ashell docs with more info

---

src/zjs_i2c_handler.c

[I2C] Fixing I2C for FRDM-K64f which uses a different bus name

---

src/zjs_error.c
src/zjs_error.h
src/zjs_util.c
src/zjs_util.h

These are from my board-api branch but not specific to it.

New util error funcs

---

README.md

[readme] Remove remaining references to dfu-all

---

src/zjs_event.c

- tests/test-events.js uncovered several bugs
- Fixed one issue in the test which was incorrectly testing

Fixed multiple bugs in events

---

src/zjs_timers.c

[timers] Fixed timers to remove timeout's properly 

---

samples/TrafficLight.js

This was the worst traffic light controller in the world, warning you
with a yellow when the light was about to turn green, instead of red.
Note: Yellow is still represented by a green LED. ;)

[samples] Fix TrafficLight.js logic

---

arc/src/main.c
scripts/analyze.sh

[sensor] Rebase code after Zephyr changed its API

---

README.md

[readme] Update to remove reference to unused stable tag

---

Makefile

New TARGET_OS variable set to either zephyr or linux, used to decide
whether to check for ZEPHYR_BASE.
Only report RAM/ROM allocation when actually building images for
arduino_101, not make clean/pristine, etc.
Detect linux target even when multiple targets are specified.
Also, only check for RAM and ROM when we're targetting arduino_101.

[build] Fix bug where ZEPHYR_BASE check was no longer happening

---

Makefile
Makefile.zephyr

[build] Fix ZEPHYR_BASE check

---

src/zjs_timers.c

[timers] Fix error if timers were called with arguments

---

scripts/analyze.sh
scripts/trlite

[ocf/aio] Fix bad config options for OCF and analog

---

Makefile
Makefile.linux
src/main.c
src/zjs_callbacks.c
src/zjs_util.c
src/zjs_util.h

[error] Better JS error printing in main loop

---

samples/OcfSensorServer.js

[ocf] Add a sensor sever

---

Makefile
Makefile.ocf_zephyr
src/zjs_ocf_ble.c
src/zjs_ocf_common.c

[ocf] Device name and BLE address set on command line

---

src/zjs_callbacks.c

[callbacks] Fix a few more memory leaks in callbacks

---

docs/ocf-ble.md

[docs] Tweak OCF over BLE doc based on my runthrough today

---

Makefile.linux
Makefile.ocf_zephyr
src/zjs_ocf_ble.c
src/zjs_ocf_common.c
src/zjs_util.c
src/zjs_util.h

- OCF debugging was enabled by default, now controlled by VARIANT
- Fixed two warnings in OCF

[ocf] Fixed OCF debug flags

---

src/zjs_promise.c

[promise] Acquire this before returning

---

samples/OcfSensorServer.js

[ocf] Changed sensor sever to remove unused properties

---

docs/API.md
docs/ocf.md

[docs] API docs for OCF server

---

samples/OcfSensorServer.js
samples/OcfServer.js

Drop the BLE address setting since we can do it from the command line.
Add copyrights and short description.

[ocf] Small tweaks to samples

---

samples/OcfServer.js
src/zjs_ocf_common.c
src/zjs_ocf_common.h
src/zjs_ocf_server.c

[ocf] Added OCF device and platform objects

---

samples/I2C.js
samples/I2CBMP280.js

This fixes issue 642 where no words showed up on the
FRDMK64F

[bugfix] Fix for no words on FRDMK64F

---

tests/test-udp4-server-manual.js
tests/test-udp4-server.js
tests/test-udp6-server-manual.js
tests/test-udp6-server.js

**ISSUES:**
#758 [udp] Throw out error with building UDP server in qemu
#761 [udp] Cannot bind other ip except '192.0.2.1' and '2001:db8::1'
**TOTAL:**  34 of 34 passed

[tests] Add tests for UDP Server APIs with IPv4 and IPv6

---

docs/API.md
docs/sensors.md

This will cover Accelerometer, Gyroscope and Ambient Light sensors.

[doc] Added documentation for W3C Generic Sensor API

---

Makefile.linux
src/zjs_callbacks.c
src/zjs_callbacks.h
src/zjs_modules.c
src/zjs_promise.c
src/zjs_test_promise.c
src/zjs_test_promise.h
tests/stress/test-promise-stress.js
tests/test-promise.js

- Also made promises work asynchronously

[promise] Test promises module

---

docs/API.md

[docs] Add UDP link to API.md

---

Makefile.linux
Makefile.ocf_zephyr
samples/OcfClient.js
scripts/analyze.sh
src/zjs_ocf_client.c
src/zjs_ocf_common.h

[ocf] Re-enable and clean up OCF client module

---

docs/console.md

[docs] Added docs about console format specifiers

---

tests/test-a101-pins.js
tests/test-aio.js
tests/test-ble.js
tests/test-buffer-rw.js
tests/test-buffer.js
tests/test-error.js
tests/test-eval.js
tests/test-gpio.js
tests/test-grovelcd.js
tests/test-i2c.js
tests/test-k64f-pins.js
tests/test-performance.js
tests/test-pwm.js
tests/test-timers.js
tests/test-uart.js

[tests] Import Assert module for all test cases

---

README.md

Update README.md to fix bad url and change the name of zephyr-SDK.

[docs] Update README.md to fix bad url

---

samples/SensorBLEDemo.js

[demo] Initial implementation of Accel/Gyroscope sensor over BLE demo

---

samples/SensorBLEDemo.js

[demo] SensorBLEDemo.js: Change device name and URL

---

docs/ocf.md

[docs] Update OCF-BLE MAC address

---

README.md

[docs] Update command for Linux module

---

samples/OcfClientUpdate.js
src/zjs_ocf_server.c

[ocf] Fix server return code on update

---

src/zjs_fs.c
src/zjs_fs.h
src/zjs_modules.c
tests/test-fs.js

- cleanup routine to free any open FD's

[fs] Change FD's to numbers instead of objects

---

src/zjs_ocf_client.c

[ocf] Add platform info to client callback

---

docs/ocf.md
src/zjs_ocf_ble.c
src/zjs_ocf_ble.h
src/zjs_ocf_common.c

- Moved setBleAddress() to ocf object

[ocf] Added OCF client documentation

---

docs/ble.md

[doc] Fix link for ble.md doc

---

README.md
docs/ble.md

Fix ble doc zjs-0.2 release

---

src/zjs_error.c
src/zjs_error.h

[error] Print JS function where error was thrown

---

src/zjs_aio.c
src/zjs_callbacks.c
src/zjs_callbacks.h
src/zjs_event.c
src/zjs_promise.c

[callbacks] Remove unused return value argument to post functions

---

samples/AmbientLight.js

This should address the bug #531

[doc] Update AmbientLight sample wiring instructions

---

src/main.c
src/zjs_modules.c

[general] Fix build breakage: use non-const script str in Linux build

---

src/main.c
src/snapshot.c
src/zjs_a101_pins.h
src/zjs_aio.h
src/zjs_ble.h
src/zjs_buffer.c
src/zjs_buffer.h
src/zjs_callbacks.c
src/zjs_callbacks.h
src/zjs_dgram.h
src/zjs_error.h
src/zjs_gpio.h
src/zjs_grove_lcd.h
src/zjs_i2c.h
src/zjs_k64f_pins.h
src/zjs_modules.h
src/zjs_ocf_client.c
src/zjs_ocf_client.h
src/zjs_ocf_common.c
src/zjs_ocf_common.h
src/zjs_performance.h
src/zjs_pwm.h
src/zjs_sensor.h
src/zjs_timers.c
src/zjs_uart.h
src/zjs_util.h

Rebased code to remove compile warnings

[jerryscript] Update JerryScript to latest master

---

src/zjs_event.c

This was breaking the WebBT demo.

[events] Fix bug from recent ZVAL patch

---

tests/test-buffer.js

- writeUInt8(-1) is not a valid check point following Buffer API

[Buffer] Remove invalid case

---

LICENSE
Makefile
Makefile.linux
src/Makefile.base
src/ashell/Makefile

These have reached code-like significance and effort.
Also, clean up a few things.

[general] Add some copyrights to some makefiles

---

.travis.yml
scripts/trlite

VM1 is taking ~14min so this should cut us down to ~7min.

[trlite] Split out a fourth VM to reduce Travis latency

---

samples/AmbientLight.js
samples/Gyroscope.js
scripts/analyze.sh

Update the sample that was still using the old Sensor api

[sensor] Update AmbientLight.js sample

---

scripts/trlite

[trlite] Fix unfinished argument documentation in last patch

---

samples/FsAsync.js
samples/FsSync.js
tests/test-fs.js

[general] Add copyright headers to recently added filesystem tests

---

README.md

[readme] Update with new python-yaml dependency in Zephyr

---

README.md

[readme] Fix format of some markdown links so they actually work

---

modules/GenericSensor.js

Add 'unconnected' state to test sensor module and fix result time.

[test] Update test sensor module to add 'unconnected' state

---

README.md

[docs] Changed Linux docs to reflect new --noexit flag

---

docs/ashell.md
src/ashell/shell-state.c

[docs] Updating ashell docs

---

scripts/trlite

[trlite] Perform runtime tests on Linux trlite job

---

tests/test-ocfclient.js
tests/test-ocfserver-bleaddr-manual.js
tests/test-ocfserver.js

**ISSUES:**
[ISS#808](https://github.com/01org/zephyr.js/issues/808) [ocf]Improve the information for resource and platform
[ISS#810](https://github.com/01org/zephyr.js/issues/810) [ocf] The request.resource.properties data is undefined
[ISS#876](https://github.com/01org/zephyr.js/issues/876) [REG] [ocf] Cannot set BLE-address for OCF server
**TOTAL:**  23 of 26 passed

[tests] Add test case for OCF APIs

---

src/main.c

- Non error returns should return 0, error should return 1

[general] Main loop should return error/success, not only error

---

src/zjs_util.h

[general] Add ability to check arguments, and handle as you see fit

---

README.md

[readme] Update networking with qemu section w/ more detail

---

docs/buffer.md

[buffer] Update docs to reflect constructor behavior

---

tests/test-fs.js

[fs] Fixed FS test failure (#886)

---

docs/ashell.md
src/ashell/shell-state.c

[docs] Making ashell docs consistant with console output

---

tools/snapshot.c

[snapshot] Removed dbg print and redireted error to stderr

---

src/zjs_ocf_server.c

[ocf] Fixed null termination bug

---

src/ashell/comms-shell.c
src/ashell/comms-uart.h

[ashell] Adding backspace key functionality

---

scripts/trlite

[trlite] Only pester Intel folks about updating copyright year

---

scripts/analyze.sh

[analyze] Fix OCF client or server being allowed but not both

---

samples/FsAsync.js
scripts/analyze.sh
scripts/trlite
src/zjs_fs.c

[fs] Enable FS async API's automatically if script uses them

---

src/zjs_fs.c

[fs] fix build warnings latest 0.9 SDK

---

docs/sensors.md
samples/BMI160Accelerometer.js
samples/BMI160Gyroscope.js
samples/SensorBLEDemo.js

Renaming both Accelerometer and Gyroscope samples to
indicate they are BMI160 specific

[samples] Added missing colon and renamed samples

---

arc/src/main.c
docs/sensors.md
samples/BMI160Temperature.js
scripts/analyze.sh
scripts/trlite
src/zjs_sensor.c

Refactor ARC code to support temperature sensors, also added
new sample BMI160Temperature.js that monitors the BMI160 sensor

[sensor] Add support for TemperatureSensor

---

src/zjs_callbacks.c
src/zjs_callbacks.h

[callbacks] Store file/func info in callbacks for debug build

---

tests/test-ocfclient.js

Fix bug #810 and be based on #947 .
**TOTAL:** 12 of 14 passed

[tests] Update test-ocfclient.js for bug fix

---

scripts/analyze.sh
scripts/trlite

- Fixed analyze so that it wont compile in FS async with
ashell builds

[trlite/analyze] Changed trlite back to ROM=250

---

src/zjs_promise.c

[promise] Set callback ID to -1 after removing them

---

Makefile
Makefile.ocf_zephyr
scripts/analyze.sh
src/Makefile.base
src/zjs_dgram.c

Fixes #947
- Removed QEMU specific option
- Added 6lowpan support for A101

[dgram] Fix garbage dgram output

---

.travis.yml

[travis] Cache the SDK directory to speed up builds drastically

---

scripts/analyze.sh
src/Makefile.base
src/zjs_test_promise.c

[test_promise] Enable test_promise module on A101

---

samples/UDPEchoServ6.js

[dgram] Added ip route info to IPv6 sample

---

src/zjs_util.c

[util] Switch to unsigned int version of __builtin_clz

---

src/zjs_buffer.c
src/zjs_util.h
tests/test-buffer.js

[buffer] Update Buffer test to allow out of memory errors

---

docs/k64f_pins.md

[docs] Update with latest info on GPIO pins working for k64f

---

src/zjs_pinmux.c

[i2c] Fix bug where pinmux is screwing up I2C

---

tests/test-k64f-pins.js

**Issue:** #990 
**ToTal:**  74 of 75 passed

[tests] Add testpoint for D3 D5 D14 D15 on K64f

---

README.md

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

Make these commands more end-user friendly (easier to copy)

---

docs/ashell.md
docs/ocf-ble.md

[docs] Tweak text boxes w/ interactive commands in ashell/ocf

---

docs/ashell.md

[docs] Adding URL to the IDE to the docs

---

src/zjs_callbacks.c
src/zjs_ocf_client.c

[callbacks] Fix memory leak in callbacks (debug build only)

---

tests/test-grovelcd.js

[tests] Restore UT for test-grovelcd.js

---

README.md

[docs] Fix K64 build instructions

---

.travis.yml
README.md
scripts/trlite
scripts/zjsbanner

A good, fun Friday task. Now no one will be without lovely banner text,
not even Mac users or people who don't install sysvbanner.

[zjsbanner] Add our own banner script

---

scripts/README

[scripts] Update the scripts/README file that was way out of date

---

scripts/analyze.sh
src/zjs_ocf_common.c

[ocf] Fix OCF on QEMU build

---

docs/console.md
samples/OcfSensorClient.js

A sample was referenced in OCF docs but never added
Fixes #1007

[docs/ocf] Fix console doc link and add sample for OCF

---

Makefile
samples/TCPClient6.js
samples/TCPEchoServ6.js
scripts/analyze.sh
src/Makefile.base
src/zjs_modules.c
src/zjs_net.c
src/zjs_net.h

[net] initial net module commit

---

src/ashell/comms-shell.c
src/ashell/comms-uart.c
src/ashell/file-utils.h
src/ashell/jerry-code.c
src/ashell/jerry-code.h
src/ashell/shell-state.c

Now javascript files that contain require("file.js") will load
that javascript module before running the javascript.  It is
recursive as well, so files that get included will have their
requires checked as well.

[ashell] Adding javascript module functionality

---

docs/ble.md

[docs] Clarify description of 256K x86 partition in BLE doc

---

src/zjs_modules.c

[modules] Acquire instance when returning in subsequent require calls

---

src/ashell/jerry-code.c
src/main.c
src/zjs_modules.c

[ashell] Move common init code to zjs_modules.c for main/ashell

---

src/zjs_unit_tests.c

[unit tests] Add unit tests for C callbacks

---

docs/ble.md

[docs] Fix link for ble.md

---

src/ashell/jerry-code.c
src/ashell/shell-state.c

This follows e.g. a similar guard in zjs_modules.c.

[ashell] Add ifdef guards for some arduino_101 specific code.

---

modules/GenericSensor.js
tests/test-bmi160accelerometer.js
tests/test-bmi160gyroscope.js
tests/test-bmi160temperature.js

**ISSUE:**  #1055 
**TOTAL:**  17 of 18 passed

[tests] Add test case for BMI160 temperature sensor and add controller check for all sensor case

---

Makefile.linux
scripts/analyze.sh
scripts/trlite
src/Makefile.base
src/zjs_callbacks.c
src/zjs_modules.c
src/zjs_test_callbacks.c
src/zjs_test_callbacks.h
tests/test-callbacks.js

- Can directly create/call/remove callbacks from JS in order to
test JS callbacks
- Fixed several bugs in callbacks that were found using this test
- Added test to trlite

[tests] Callback testing module

---

README.md

[doc] Update Mac build instructions

---

samples/TCPClient6.js
samples/TCPEchoServ6.js

[net] More descriptive comments in Net samples

---

scripts/analyze.sh

[net] Fix net module on K64f

---

src/ashell/comms-shell.c
src/ashell/comms-uart.c
src/ashell/ihex-handler.c

[ashell] Fixing ihex on single thread ashell

---

src/zjs_util.c
src/zjs_util.h

[ashell] Fix ashell after it broke with semaphore change

---

src/zjs_fs.c
src/zjs_timers.c
src/zjs_unit_tests.c
src/zjs_util.h

[general] Linked list macros to simplify code

---

docs/API.md
docs/net.md

[docs] Docs for net module

---

docs/API.md
docs/web-socket.md

[docs] Web socket documentation

---

src/ashell/file-utils.c

[ashell] Remove error print if a cfg file doesn't exist

---

Makefile.linux
Makefile.ocf_zephyr
docs/ocf.md
samples/OcfClient.js
samples/OcfClientUpdate.js
samples/OcfDeviceInfo.js
samples/OcfPlatformInfo.js
samples/OcfSensorClient.js
samples/OcfSensorServer.js
samples/OcfServer.js
src/zjs_ocf_client.c
src/zjs_ocf_common.c
src/zjs_ocf_common.h
src/zjs_ocf_config.h
src/zjs_ocf_server.c

- Now, multiple resources can be registered

[ocf] Added start API to ocf object

---

tests/test-a101-pins.js
tests/test-k64f-pins.js

**TOTAL:** 
a101: 82 of 82 passed
k64f: 104 of 105 passed

[tests] Add weak pull-up check and weak pull-down check

---

src/zjs_callbacks.c

[callbacks] Fixed signal callback if ID is out of bounds

---

scripts/trlite
src/zjs_mbedtls_config.h

[ws] Forgot to check in websocket file

---

src/zjs_net.c

[net] Add null pointer check to tcp_recv

---

scripts/zjsbanner

[zjsbanner] Improve code size, importantly

---

scripts/trlite

[trlite] Consolidate tests for quicker VM1 build time

---

scripts/trlite

[trlite] Run JS tests with a new bash function for better output

---

tests/test-pwm.js

**ISSUE:** #1099 
**TOTAL:** 12 of 12 passed

[pwm] Fix timer error range on setTimeout function

---

src/zjs_ocf_server.c

[ocf] Moved UUID code to after resource is registered

---

tests/test-callbacks.js

**Fix bug:** #1116 
**TOTAL:** 41 of 41 passed

[tests] Fix asynchronous sequential on test-callback.js for K64f

---

tests/test-ocfserver-bleaddr-manual.js

[tests] Add 6LoWPAN test on ocf server

---

tests/test-ocfserver.js

[tests] Add start api and multiple resources for OCF server

---

src/zjs_fs.c

[fs] Add size to stats object

---

src/zjs_fs.c

[fs] Fix fs.close() API

---

src/zjs_web_sockets.c

[ws] Fix K64F websocket build break

---

Makefile
Makefile.linux
scripts/trlite
src/main.c
src/zjs_callbacks.c
src/zjs_util.c
src/zjs_util.h

- Iterate through global object to find the function name

[general] Print function names in error messages

---

.travis.yml

[travis] Update to use SDK 0.9

---

scripts/trlite

[trlite] Fix output of linux tests when run with -l

---

scripts/trlite
src/zjs_fs.c

[fs] Added readFile/readFileSync APIs

---

src/zjs_ocf_common.h

[ocf] Increase resource type string length

---

src/zjs_fs.c

[fs] Fix issue where it the max string it can write is 256

---

src/zjs_fs.c
tests/test-fs.js

[fs] Fix FS so it overwrites w and w+ file modes

---

src/ashell/shell-state.c
src/ashell/shell-state.h

Also, fix description of ls, reorder command list for clarity, improve
help formatting.

[ashell] Simplify help command list for IDE

---

docs/ashell.md

Update Windows instructions in ashell docs and mention how to
install the WinUSB driver with the Zadig utility.

[ashell] Update Windows instructions

---

docs/ashell.md

Following previous commit, add missing instruction
for windows setup.

[ashell] Add missing instruction for windows setup

---

Makefile
scripts/trlite

[general] Turn on jerryscript error messages

---

README.md

Update latest stable version to 0.3 in README.md
Signed-off-by: Belem Zhang <belem.zhang@intel.com>

[docs] Update latest stable version to 0.3 in README.md

---

src/ashell/ihex-handler.c

[ashell] Fixing a leak in ihex

---

samples/OcfSensorServer.js

[sample] Update OcfSensorServer.js for bug fix

---

src/ashell/comms-shell.c
src/ashell/comms-uart.c
src/ashell/comms-uart.h

[ashell] Further fixes for character duplication in ashell

---

README.md
docs/ashell.md

[doc] Update Ashell/IDE instructions

---

Makefile
scripts/trlite

[ide] Added function name in error to ide by default

---

src/zjs_util.c

- When printing out the error message function, this will
search up the object tree to find the full object path
of the function.

[util] Search up the object hierarchy for full function path

---

src/zjs_ocf_server.c

[ocf] Remove code that was previously removed in OCF

---

Makefile

[make] Use -j option in zephyr make

---

src/zjs_ble.c

[ble] Fix ble callbacks time out after promise patch

---

docs/pme.md

[pme] Fix PME sample url for pme.md doc

---

samples/PME.js

[pme] Fix PME classifier mode for PME.js sample

---

samples/Stepper.js

Add a sample file for the Grove 28BYJ-48 stepper motor
Signed-off-by: James Ausmus <james.ausmus@intel.com>

[samples] Adding Stepper.js sample

---

tests/test-board-manual.js

[tests] Add test case for board APIs

---

tests/test-ocfclient.js
tests/test-ocfserver.js

[ocf] Add start function and multiple resources for OCF test cases

---

samples/OcfDeviceInfo.js
samples/OcfPlatformInfo.js

[sample] Change resource type to get device and platform information

---

docs/net.md

[net] Update the type of 'family' attribute to same as sample

---

samples/TCPClient6.js

[net] Update tcp client to add 'enter' for finished transmission

---

tests/test-ble.js

[tests] Add multiple clients tests for BLE APIs

---

README.md

- K64F: File System, OCF, Dgram, Net
- F411RE: Buffer, Console, Event, File System, Performance, Timers

Update status of supported modules in README

---

src/zjs_ocf_client.c
src/zjs_ocf_common.c

[ocf] Fix ocf compilation error on Mac

---

tests/test-ble.js

[ble] Fix bug for test-ble.js

---

src/zjs_ipss.json
src/zjs_net_config.json

[ipss] Make ipss inclusion its own module

---

scripts/analyze

[analyze] Sort dependencies before listing them

---

.gitmodules

Moved Zephyr git repo from gerrit to github

[git] Update Zephyr submodule git repo to github

---

src/zjs_sensor.c

[sensor] Fixed sensors cannot be stopped in polling mode

---

src/zjs_ocf_client.c

The promise object needs to be acquired and released later
Fixes #1194

[ocf] Fixed OCF Client not able to connect

---

scripts/trlite

[ocf] Updated iotivity-constrained

---

tests/test-ws-client-node.js
tests/test-ws-server.js

**ISSUE:** #1150  #1234 
**TOTAL:** 14 of 14 passed
**Commit ID:** bd07595

[tests] Add test case for WebSocket APIs

---

tests/test-tcp6-client.js
tests/test-tcp6-server.js
tests/tools/test-socket-client.py
tests/tools/test-socket-server.py

[tests] Add test case for tcp API

---

docs/spi.md
src/zjs_spi.c

[SPI] Adding docs for SPI.  Also adding a NULL check

---

src/zjs_json.json
src/zjs_pme.json

[json] Support JSON using JerryScript

---

src/zjs_fs.json

[fs] Fixed broken FileSystem module on FRDM-K64F

---

tests/test-pme.js

**ISSUE:**  #1243 #1244 #1245 #1246  #1249 
**TOTAL:** 73 of 78 passed

[tests] Add test case for PME APIs

---

scripts/trlite

[trlite] Add testing of all the modules that should work on k64f

---

samples/thermostat/README.md
samples/thermostat/th02-ess.js
samples/thermostat/th02-ocf.js
samples/thermostat/th02.js

This adds example code of building a ZJS based thermostat using the Grove Temperature & Humidity Sensor.
Signed-off-by: Tonny Tzeng tonny.tzeng@intel.com

[sample] New sample code of building a TH02 based thermostat

---

Makefile

[modules] Fixing including JS modules that include arc modules

---

src/zjs_ocf_common.c
src/zjs_ocf_server.c
src/zjs_web_sockets.c

[general] Fix build breakage on FRDM-K64F and QEMU

---

samples/PMESaveRestore.js

[pme] Fix small bug for pme sample

---

docs/pme.md

[pme] Update PME doc for adding save and restore APIs

---

samples/SPI.js
src/zjs_spi.c

Also updating the example to demonstrate this.

[spi] SPI.transceive can now be passed a Buffer object.

---

samples/FXOS8700Magnetometer.js
src/sensors/zjs_sensor_magn.c
src/sensors/zjs_sensor_magn.h
src/zjs_common.h
src/zjs_sensor_board_k64f.c
src/zjs_sensor_magn.json

It will support the fxos8700 magnetometer sensor on the FRDM_K64F

[sensor] Added Magnetometer sensor support

---

src/zjs_sensor_board_k64f.c

[sensor] Fixed Accelerometer always the same value on K64F

---

src/zjs_fs.c

[fs] Fixed file system failed to build on k64f

---

src/zjs_pme.c

[pme] Fix API parameter bugs

---

samples/SPI.js
src/zjs_spi.json

[SPI] Fixing SPI on K64f

---

Makefile
src/Makefile.base
src/zjs_ashell.json
src/zjs_ashell_cli.json
src/zjs_ashell_ide.json

[ashell] Fix to allow command line ashell to be built.

---

src/zjs_pinmux.c

[spi] Adding an ifndef for the K64f SPI pins

---

.travis.yml
arc/src/arc_aio.c

[zephyr] Update to Zephyr 1.8.0

---

tests/test-ble.js

[ble] Fix small bug

---

arc/src/arc_curie_pme.c

[pme] Fix small bug for 1343

---

scripts/analyze

[analyze] Print JSON file and error if decode fails

---

.travis.yml

[travis] Experiment from suggestion on #travis

---

docs/net-config.md

[net-config] Update net-config.md

---

samples/DHCP.js

[dhcp] Update samples/DHCP.js

---

src/zjs_ocf_client.c

This is a work-around patch to have the tests no segfault
when the function passed into the .then() is empty, which
causes a segfault executed.
Fixes #1316

[ocf] Work-around to fix segfault when using promises

---

src/main.c
src/zjs_ble.c
src/zjs_modules.c
src/zjs_sensor.c

[build] Fixed linux build error on MacOS

---

src/zjs_net_config.c

For some reason, perhaps a good one, the top two bits of the BLE address
are always set regardless of what we try to set it to. So this patch will
warn the user about that and update the address we print out in debug
mode.

[net-config] Fix BLE addresses given that top two bits are always set

---

src/zjs_web_sockets.c

[websockets] Fix for websockets issue #1348

---

src/zjs_callbacks.c

[callbacks] Adjust cb_size in new_id() instead of every call site

---

tests/test-pme-save-restore.js

I add this test point to [tests/test-pme.js](https://github.com/01org/zephyr.js/blob/master/tests/test-pme.js), but I have a issue `[FATAL]: 10`. 
So, I create a new file to test this.
**TOTAL:** 1 of 1 passed

[tests] Add test case for PME save and restore APIs

---

tests/test-6lowpan-ocfserver-manual.js

[tests] Remove OCFObject.setBleAddress test point

---

modules/GenericSensor.js
tests/test-magnetometer.js

[tests] Add test case for magnetometer sensor on FRDM-K64F

---

scripts/trlite

[trlite] Build PME and Magnetometer in travis

---

src/zjs_ocf_client.c

[ocf] Fixed dataModels not set in OcfClient

---

samples/SPI.js
src/zjs_spi.c

[SPI] Fix for #1326 - Only zeros on SPI with K64F

---

docs/ocf.md
samples/OcfSensorServer.js
samples/OcfServer.js
src/zjs_ocf_server.c
tests/test-ocfserver.js

Update API of OCF Server Request and all the samples so
they are in sync with API doc.
Also fixes some typos in the tests.
Fixes #1334

[ocf] Fix OCF Server Request API

---

docs/net.md
samples/TCPClient6.js
tests/test-tcp6-client.js

[docs] Removed onup event from net, now in net-config

---

docs/uart.md
tests/test-uart-read-manual.js
tests/test-uart.js

- Update uart tests to remove promise.
- Remove promise in uart doc because write return void now.

[tests] Update uart tests and doc for promise removed

---

docs/buffer.md
src/zjs_buffer.c
tests/test-buffer.js

[buffer] Add fill API

---

src/zjs_net_config.c

[net-config] Update setStaticIP() function API

---

tests/test-spi.js

[tests] Update test-spi.js to support K64f

---

src/zjs_net_config.c

[net-config] Can trigger 'ondown' event

---

docs/buffer.md

[docs] Update buffer.md for link fix

---

tests/test-ws4-server-dhcp.js
tests/test-ws6-server.js
tests/tools/test-ws4-client-dhcp.js
tests/tools/test-ws6-client.js

[tests] Add test case for WS APIs about IPv4 with DHCP mode

---

tests/test-dhcp-ws-manual.js
tests/tools/test-dhcp-ws-client.js

[tests] Add test case for DHCP APIs with websocket

---

Makefile.linux
src/zjs_script.c

[board] Re-enable board API for Linux build, inadvertently lost

---

samples/tests/Events.js

[event] Print all event names

---

samples/websockets/WebSocketServer.js
samples/websockets/WebSocketServer4.js
src/zjs_web_sockets.c

[websockets] Fix close connection after event patch

---

samples/TCPEchoServ4.js

[net] Update server IPv4 address

---

docs/ble.md

[docs] Update ble.md to fix link and add parameter for setServices()

---

src/zjs_fs.json

[fs] Fixed filesystem not printing on FRDM-K64F

---

tests/test-process-linux-manual.js

[tests] Add test case for process API on Linux

---

src/zjs_buffer.c
src/zjs_event.c

Fixes compilation erros on casting and unused variable
Fixes #1440

[build] Fixed build error on MacOS

---

tests/tools/test-tcp6-server.py

1. Update test-tcp6-server.py for connection
2. Enable 'Ctrl+C' for server stoped

[tests] Update test-tcp6-server.py for connection

---

tests/test-6lowpan-ocfserver-manual.js

[tests] Update test-6lowpan-ocfserver-manual.js for default value

---

docs/ble.md
docs/net-config.md
docs/net.md
docs/ocf.md
docs/uart.md
docs/web-socket.md

[docs] Move to a common Node.js-like format for documenting events

---

README.md

[readme] Fix instructions for connecting ENC28J60 board

---

src/ashell/comms-uart.c

[ashell] Fix for UART not showing text properly

---

src/zjs_callbacks.c

[callbacks] Finish removing JS callback lists feature

---

README.md

[doc] Update instructions for building nRF52 DK board

---

modules/ST7735.js
samples/SPI_Screen.js
src/zjs_spi.c

New module for the ST7735 screen which uses SPI for communication.  Also some minor SPI fixes.

[SPI] New SPI screen module and SPI fixes

---

src/zjs_spi.c

[SPI] Fixing RX obj so that it doesn't get freed upon return.

---

tests/test-spi.js

[spi] Remove test point for test-spi.js

---

src/main.c
src/zjs_callbacks.c
src/zjs_event.c
src/zjs_event.h
src/zjs_net.c
src/zjs_util.h
src/zjs_web_sockets.c
tests/test-dhcp-ws-manual.js
tests/test-ws4-server-dhcp.js

Still not working but I'm looking for some early review. This is working toward fixing #1458.

Ws fix bus fault

---

tests/test-tcp6-client.js
tests/tools/test-tcp4-client-dhcp.py
tests/tools/test-tcp4-client.py
tests/tools/test-tcp6-client.py

[tests] Update error name and add keyboard interrupt

---

tests/test-tcp4-client.js
tests/tools/test-tcp4-server.py

[tests] Add test case as tcp4 client for TCP APIs

---

samples/Stepper.js

[sample] Update Stepper.js to work well and obviously

---

tests/test-ws4-server.js
tests/tools/test-ws4-client.js

[tests] Add test case for ws4 APIs

---

src/zjs_web_sockets.c

The check for max_payload was checking the total TCP packet
length rather than just the websocket data payload length.
This caused the initial accept packet to be rejected if
the maxPayload property was set to less than 276.

[websockets] Move max payload check to check data payload

---

src/zjs_util.h

[utils] Add comment documenting usage of CHECK_REF_COUNT

---

src/zjs_net.c

[net] Distinguish some identical debug messages; print rvals

---

Makefile
src/Makefile.base
src/zjs_common.h

[debug] Add VERBOSITY flag to control debug output verbosity

---

Makefile

[build] Make will now error if JS= is given when building ide / ashell

---

src/zjs_iotivity_constrained.json
src/zjs_ocf.json
src/zjs_ocf_client.c
src/zjs_ocf_common.h
src/zjs_ocf_server.c

This updates iotivity-constrained to latest to support OCF 1.0 spec.
Fixes #1485

[ocf] Update iotivity-constrained to latest

---

README.md

[general] Update README to refer to 0.4 as the latest stable release

---

samples/SensorBLEDemo.js
samples/WebBluetoothGroveLcdDemo.js

[sample] Support multi client for bug fix

---

docs/API.md
docs/webusb.md
samples/WebUSB.js
src/zjs_webusb.c
src/zjs_webusb.h
src/zjs_webusb.json

[webusb] Add new WebUSB module to support URL advertising

---

README.md

[docs] Update READNE.md for pip3 installed

---

src/zjs_web_sockets.c

[websockets] Fix for misspelled HTTP header

---

src/zjs_board.c

[k64f] Update board.c for bug fix

---

docs/buffer.md
src/zjs_buffer.c
tests/test-buffer.js

[buffer] Add utf8 encoding for toString (default as in Node)

---

samples/WebUSBConfig.js
src/zjs_buffer.c

Finished initial version of WebUSBConfig sample, which demonstrates how you could use WebUSB to configure settings on an otherwise headless device.

Webusb config

---

samples/WebUSBConfigGroveLCD.js

[samples] Add new version of WebUSBConfig sample w/ Grove LCD

---

README.md

Add a pointer to the security reporting procedure on 01.org

[docs] Add instructions on how to report security issues

---

samples/WebUSBConfig.js
samples/WebUSBConfigGroveLCD.js

[samples] Fixed JS styling

---

tests/test-webusb-manual.js

[tests] Add test case for WebUSB APIs

---

docs/mathstubs.md
samples/Random.js
src/zjs_math.c
src/zjs_math.h
src/zjs_math.json

[util] Added Math.random() api

---

Makefile
src/ashell/jerry-code.c
src/main.c

[cleanup] Removing unused commented code for mem pools

---

docs/gfx.md

[docs] Update gfx.md for bug fix

---

samples/AIO.js
tests/test-aio.js

[tests] Update test and sample case to support K64f board

---

Makefile

[build] Fixed build error when IDE_GPIO_PIN is not set

---

src/zjs_aio.c
src/zjs_aio_a101.c

[aio] Adding needed changes for AIO to work on A101

---

src/zjs_aio.c
src/zjs_modules.c
src/zjs_modules.h
src/zjs_sensor_board_k64f.c

[modules] Adding zjs_unregister_service_routine function

---

docs/net-config.md
samples/TCPClient6.js
samples/TCPEchoServ4_DHCP.js
samples/websockets/WebSocketServer4.js
src/zjs_net_config.c
src/zjs_net_config.h
src/zjs_net_config.json
tests/test-dhcp-ws-manual.js
tests/test-tcp4-server-DHCP.js
tests/test-tcp6-client.js
tests/test-ws4-server-dhcp.js

Jerry modules don't support '-' in the name.  Renaming net-config
to net_config.

[net] Jerry module fix for net

---

src/zjs_board.c

[board] Wrapping code in #if statement to fix compiler issues

---

docs/6lowpan-ble.md
samples/OcfClient.js
samples/OcfClientUpdate.js
samples/OcfDeviceInfo.js
samples/OcfPlatformInfo.js
samples/OcfSensorClient.js
src/zjs_buffer.c
src/zjs_iotivity_constrained.json
src/zjs_ocf.json
src/zjs_ocf_common.c
src/zjs_ocf_config.h

Updated iotivity-constrained with latest 6lowpan fixes,
and updated 6lowpan configs to work with latest Zephyr 1.9

[ocf] Updated OCF 6lowpan

---

tests/test-gfx-negative-manual.js
tests/test-gfx-positive-manual.js

ISSUE: #1627 #1648 #1649 #1650 
**TOTAL:** 1 of 2 passed

[tests] Add test case for GFX APIs

---

src/zjs_webusb.c

[webusb] Removing commented code

---

tests/test-a101-pins.js

[tests] Update test case for new open api

---

tests/test-pwm.js

Add some test points for PWM open API and support on K64f test
**ISSUE:** #1667 
**TOTAL:** 16 of 16 passed

[tests] Add test points for PWM.open() API

---

tests/test-gpio.js

**TOTAL:**  
18 of 18 passed for A101 and Linux
21 of 21 passed for K64f

[tests] Add test points for gpio APIs

---

samples/WebBluetoothDemo.js
samples/WebBluetoothGroveLcdDemo.js

[sample] Update aio sample to EventEmitter

---

src/ashell/file-utils.c
src/ashell/file-utils.h
src/ashell/jerry-code.c
src/zjs_modules.c

[modules] Adding JerryScript module support for JS modules

---

Makefile

This will get rid of unneccessary output when running make update
Fixes #1673

[build] Fixed build log output

---

Makefile

Fixes #1669
Signed-off-by: Jimmy Huang <jimmy@Jimmys-Mac-mini.local>

[build] Fix qemu on MacOS

---

scripts/trlite
src/zjs_board.c

Fix an error I introduced before committing Brian's recent patch by
moving a line w/o adequate testing. Sorry...

[board] Fix build of board API w/o GPIO, AIO, PWM

---

src/zjs_board.c

[board] Fix K64F extra pin mappings for LED/switches

---

src/zjs_ashell.json

[build] Set the Intel's VID and PID for A101 device

---

README.md

[build] Update README.md to support k64f and nrf52 boards build on MacOS

---

src/zjs_util.c

[build] Fixed compile warning on 96b_carbon

---

samples/tests/GPIO-Inputs.js
samples/tests/GPIO-Outputs.js
src/zjs_pinmux.c

[pinmux] Fix D8 pin and support other GPIOs on k64f

---

cmake/zjs.cmake
src/zjs_util.c

[build] Fixed debug build

---

README.md

[doc] Update README.md to k64f board flashing

---

tests/test-board-manual.js

[tests] Add test point to support more stm32 board

---

.travis.yml

[travis] Add caching of cmake executable

---

tests/test-a101-pins.js

[tests] Update a101 pins test case and add test points

---

src/zjs_board.c
src/zjs_board.h
src/zjs_unit_tests.c

Supercedes #1723 
Adds unit tests that catch the issue found by @cuiyanx in #1722/#172, and then fixes it.

Board split pin name test

---

samples/WebUSB.js
src/zjs_webusb.json

[webusb] Fixing webusb popup and sample URL

---

docs/ashell.md

[docs] Update ashell.md to fix 1732

---

tests/test-k64f-pins.js

ISSUES： #1667 #1625 
**TOTAL:** 114 of 130 passed

[tests] Update K64f pins test case and add test points

---

docs/API.md
docs/boards/basic.md
docs/boards/frdm_k64f.md
samples/tests/GPIO-Outputs.js

Also, tweak a couple docs/comments I ran into along the way.

[docs] Add documentation for basic board support

---

tests/test-gfx-negative-manual.js
tests/test-gfx-positive-manual.js

[tests] Update GFX test case using new module

---

samples/WebUSBConfig.js
samples/WebUSBConfigGroveLCD.js
tests/test-webusb-manual.js

[webusb] Update 3 file for webusb popup

---

src/zjs_web_sockets.c

[build] Update zjs_web_sockets.c for build with debug flag

---

scripts/trlite

[trlite] added check for Signed-off-by line

---

tests/test-gfx-negative-manual.js
tests/test-gfx-positive-manual.js

[tests] Update GFX test case to more clear for manual tester

---

tests/test-webusb-manual.js

[tests] Update webusb test case for bug fix

---

src/zjs_sensor.c
src/zjs_sensor_light.json

[sensor] Fixed ambient light sensor pin lookup

---

src/zjs_util.c

[build] Fix linux debug build compile error

---

README.md

[readme] Simplify apt-get to apt in instructions

---

Makefile

[build] Add ROM/RAM change detection in overlay

---

src/zjs_ocf_common.c

[ocf] Fix warnings in debug build

---

src/zjs_net.c
src/zjs_net_config.c

[net_config] Fix invalid cast in zjs_net_config_get_ip

---

src/zjs_qemu_x86.json

[qemu] Increase stack size to avoid failure in network tests

---

src/zjs_gfx.c

[gfx] Draw a line correctly in special cases

---

tests/test-tcp4-server-DHCP.js

| New Test | Update Test | Delete Test | Passed | Total |
| :---: | :---: | :---: | :---: | :---: |
| | 1 | | 1 | 1 |

[tests] Update test case to get server address

---

src/zjs_timers.c
src/zjs_util.h

[timers] Checks to prevent deleting timers / memory that we shouldn't

---

tests/test-board.js
tests/test-tcp4-server-DHCP.js
tests/test-tcp4-server.js
tests/test-tcp6-server.js

| New Test | Update Test | Delete Test | Passed | Total |
| :---: | :---: | :---: | :---: | :---: |
| | 26 | | 2 | 26 |

[tests] Update test method to bug fix

---

tests/test-buffer.js

| New Test | Update Test | Delete Test | Passed | Total |
| :---: | :---: | :---: | :---: | :---: |
| 7 | | | 7 | 7 |

[tests] Update test-buffer.js to add test points

---

README.md

[doc] Update Mac instructions for building QEMU

---

src/zjs_ocf_server.c

[ocf] Fixed debug build warnings

---

cmake/zjs.cmake
src/zjs_callbacks.c

[build] Fix setting CB_STATS does not work

---

arc/src/arc_pme.c
src/zjs_event.c
src/zjs_gfx.c
src/zjs_timers.c

[general] Add missing newlines in print calls

---

src/zjs_callbacks.c

[ws] Fix networking hiccups by increasing ring buffer size

---

README.md

[docs] Update README.md for k64f board building

---

src/zjs_gfx.c

[gfx] Can set coordinate as negative number

---

src/zjs_callbacks.c

[callbacks] Fix some debug message formatting

---

Makefile

[build] Fix paths to symbol files for debug targets

---

README.md

Added PME and WebUSB to A101, and re-organized chart to be alphabetized.

[docs] Update supported components

---

Makefile
cmake/zjs_linux.cmake

[ocf] Fixed compile warnings on linux

---

src/zjs_callbacks.c

[callbacks] Eliminate compile warning

---

README.md
docs/ashell.md
samples/arduino/basics/Blink-stm32-e407.js
samples/arduino/basics/Blink-stm32f4-disc1.js
src/zjs_ashell.json
src/zjs_ashell_ide.json
src/zjs_ble.json
src/zjs_board.c
src/zjs_fs.json
src/zjs_i2c.json

[WIP] Add WebIDE support for STM32F407G-DISC1 and Olimex STM32-E407 boards.

---

README.md

[docs] Update README.md to fix URL

---

scripts/zjsbanner

Use a dict to make the zjsbanner code simpler and hopefully easier to
understand.
Signed-off-by: John L. Villalovos <john@sodarock.com>

[build] Simplify zjsbanner code

---

docs/6lowpan-ble.md

Signed-off-by: Zhang xiaoyu<xiaoyux.zhang@intel.com>
Ocf server retrieve resource method has been altered, so update relative README

Update ocf server in 6lowpan-ble.md

---

README.md

[readme] Correct text about native debug make targets

---

src/zjs_ble.c

[ble] Fixed compile warning

---

docs/6lowpan-ble.md

[doc] Sync 0.5 doc of 6lowpan-ble.md

---

README.md

Flash images to Arduino 101 should happen pretty much immediately
after the Master Reset button is pressed. Replace "After a few seconds"
with "Within a few seconds".
Signed-off-by: Ziran Sun <ziran.sun@samsung.com>

Minor change on README file.

---

src/zjs_ashell_cli.json
src/zjs_ashell_ide.json

Fix to allow new boards build CLI ashell

---

README.md

[docs] Update version to 0.5 in README.md

---

scripts/checkheaders
src/zjs_ble.c
src/zjs_ble.json
src/zjs_callbacks.c

[zephyr] Updated Zephyr to v1.11.0

---

Makefile

[build] Fix regression the make update no longer works

---

docs/ashell.md

Updating ashell docs

---

src/ashell/ide-webusb.c

Fixing IDE URL
